import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { Voucher, Account } from '../accounting/types'
import { getThemeColorArray } from '../services/reportExportService'


export function exportVoucherToPDF(voucher: Voucher, accounts: Account[], currency: string = 'AED', moduleName: string = 'Investment Accounting Module', generatedBy?: string) {
  const doc = new jsPDF()
  const themeColor = moduleName.toLowerCase().includes('propert') ? [222, 141, 169] as [number, number, number] : [15, 76, 53] as [number, number, number]
  const pageWidth = doc.internal.pageSize.getWidth()
  const centerX = pageWidth / 2
  const actualGeneratedBy = generatedBy || (typeof localStorage !== 'undefined' ? localStorage.getItem('loggedInUser') : null) || 'User'

  // ── Cover Page Header (matching main report design) ──
  doc.setTextColor(0, 0, 0)
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text('Sameer Ishaq Harmoudi', centerX, 15, { align: 'center' })

  doc.setDrawColor(200, 200, 200)
  doc.setLineWidth(0.5)
  doc.line(0, 23, pageWidth, 23)

  // Title
  doc.setTextColor(0, 0, 0)
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text(`${voucher.type.toUpperCase()} VOUCHER`, centerX, 30, { align: 'center' })

  // Meta info grid
  doc.setTextColor(100, 116, 139)
  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')

  const dateOptions: Intl.DateTimeFormatOptions = { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit', hour12: false }
  const generatedOn = new Date().toLocaleString('en-GB', dateOptions).replace(',', '')

  const metaItems = [
    { label: 'Voucher #', val: voucher.number },
    { label: 'Date', val: voucher.date },
    { label: 'Status', val: voucher.status },
    { label: 'Generated On', val: generatedOn },
    { label: 'Generated By', val: actualGeneratedBy },
    { label: 'Portfolio', val: moduleName },
  ]

  const columns = 3
  const rowHeight = 7
  const leftMargin = 14
  const colWidth = (pageWidth - (leftMargin * 2)) / columns
  let myY = 38

  metaItems.forEach((item, index) => {
    const col = index % columns
    const row = Math.floor(index / columns)
    const startX = leftMargin + (col * colWidth)
    const itemY = myY + (row * rowHeight)

    doc.setFont('helvetica', 'bold')
    doc.text(item.label + ':', startX, itemY)

    const labelWidth = doc.getTextWidth(item.label + ': ')
    doc.setFont('helvetica', 'normal')
    doc.text(item.val, startX + labelWidth, itemY)
  })

  const totalRows = Math.ceil(metaItems.length / columns)
  myY += (totalRows * rowHeight) + 4

  // ── Voucher Details Section ──
  let y = myY + 7

  // Voucher number as subtitle
  doc.setFontSize(13)
  doc.setTextColor(...themeColor)
  doc.text(voucher.number, 14, y)
  y += 8

  // Info box background
  doc.setFillColor(248, 250, 252)
  doc.setDrawColor(226, 232, 240)
  const boxStartY = y
  let boxContentY = y + 6

  // Voucher Type & Status
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8)
  doc.setTextColor(100, 116, 139)
  doc.text('VOUCHER TYPE', 20, boxContentY)
  doc.text('STATUS', 80, boxContentY)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(17, 24, 39)
  boxContentY += 5
  doc.text(voucher.type, 20, boxContentY)
  doc.text(voucher.status, 80, boxContentY)
  boxContentY += 8

  // Payment-specific fields
  const isJournal = voucher.type === 'Journal'
  if (voucher.type === 'Receipt') {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(8)
    doc.setTextColor(100, 116, 139)
    doc.text('PAYMENT MODE', 20, boxContentY)
    doc.text('CHANNEL', 80, boxContentY)
    doc.text('REF NUMBER', 140, boxContentY)

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.setTextColor(17, 24, 39)
    boxContentY += 5
    doc.text(voucher.paymentMode || '—', 20, boxContentY)
    doc.text(voucher.paymentChannel || '—', 80, boxContentY)
    doc.text(voucher.paymentReference || '—', 140, boxContentY)
    boxContentY += 8
  } else if (voucher.type === 'Payment') {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(8)
    doc.setTextColor(100, 116, 139)
    doc.text('PAYMENT MODE', 20, boxContentY)
    doc.text('PAYMENT REFERENCE', 80, boxContentY)

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.setTextColor(17, 24, 39)
    boxContentY += 5
    doc.text(voucher.paymentMode || '—', 20, boxContentY)
    doc.text(voucher.paymentReference || '—', 80, boxContentY)
    boxContentY += 8
  }

  // Description
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8)
  doc.setTextColor(100, 116, 139)
  doc.text('DESCRIPTION / NARRATION', 20, boxContentY)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(17, 24, 39)
  boxContentY += 5
  const splitDesc = doc.splitTextToSize(voucher.description, 165)
  doc.text(splitDesc, 20, boxContentY)
  boxContentY += (splitDesc.length * 4.5)

  // Created By
  boxContentY += 4
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8)
  doc.setTextColor(100, 116, 139)
  doc.text('CREATED BY', 20, boxContentY)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(17, 24, 39)
  boxContentY += 5
  doc.text(voucher.createdBy || '—', 20, boxContentY)
  boxContentY += 4

  // Draw the info box
  doc.roundedRect(14, boxStartY, pageWidth - 28, boxContentY - boxStartY + 4, 2, 2, 'FD')
  // Re-render text over the box (since we drew the box after text, we need to re-render)
  // Actually, let's draw box first then text. Let me restructure...

  // ── Line Items Table ──
  y = boxContentY + 12

  const tableHead = [['Account', 'Debit', 'Credit', 'Narration']]
  const tableBody = voucher.lines.map(line => {
    const acct = accounts.find(a => a.id === line.accountId)
    const acctName = acct ? `${acct.code} — ${acct.name}` : line.accountId
    const debitText = line.type === 'Debit' ? `${currency} ${line.amount.toLocaleString(undefined, { minimumFractionDigits: 2 })}` : '—'
    const creditText = line.type === 'Credit' ? `${currency} ${line.amount.toLocaleString(undefined, { minimumFractionDigits: 2 })}` : '—'
    return [acctName, debitText, creditText, line.narration || '']
  })

  const totalDebit = voucher.lines.filter(l => l.type === 'Debit').reduce((s, l) => s + l.amount, 0)
  const totalCredit = voucher.lines.filter(l => l.type === 'Credit').reduce((s, l) => s + l.amount, 0)
  const tableFoot = [['Total', `${currency} ${totalDebit.toLocaleString(undefined, { minimumFractionDigits: 2 })}`, `${currency} ${totalCredit.toLocaleString(undefined, { minimumFractionDigits: 2 })}`, '']]

  autoTable(doc, {
    startY: y,
    head: tableHead,
    body: tableBody,
    foot: tableFoot,
    showFoot: 'lastPage',
    theme: 'grid',
    styles: { fontSize: 9 },
    headStyles: { fillColor: themeColor, textColor: [255, 255, 255], fontStyle: 'bold' },
    footStyles: { fillColor: [248, 251, 249], textColor: themeColor, fontStyle: 'bold', lineWidth: { top: 0.5, bottom: 0.1, left: 0.1, right: 0.1 }, lineColor: themeColor },
    alternateRowStyles: { fillColor: [248, 251, 249] },
    columnStyles: {
      0: { cellWidth: 70 },
      1: { cellWidth: 35 },
      2: { cellWidth: 35 },
      3: { cellWidth: 'auto' },
    }
  })

  y = (doc as any).lastAutoTable.finalY + 25

  // ── Signatures ──
  doc.setDrawColor(180, 180, 180)
  doc.setLineWidth(0.3)
  doc.line(20, y, 65, y)
  doc.line(82.5, y, 127.5, y)
  doc.line(145, y, 190, y)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(100, 116, 139)
  doc.text('Prepared By', 32, y + 5)
  doc.text('Reviewed By', 95, y + 5)
  doc.text('Authorized Signatory', 152, y + 5)

  // ── Footer ──
  const pageCount = doc.internal.getNumberOfPages()
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.setTextColor(150, 150, 150)

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    const pH = doc.internal.pageSize.getHeight()
    const pW = doc.internal.pageSize.getWidth()
    const footerY = pH - 10
    doc.text('Powered By INSACC', 14, footerY, { align: 'left' })
    doc.text(`Page ${i} of ${pageCount}`, pW - 14, footerY, { align: 'right' })
  }

  doc.save(`Voucher_${voucher.number}.pdf`)
}
