import { jsPDF } from 'jspdf'
import { autoTable } from 'jspdf-autotable'
import * as XLSX from 'xlsx'
import { saveWithDialog } from './exportService'
import type { MonthlyTrend, AssetAllocation, CategoryBreakdown } from '../data/reports'
import { formatMonth } from '../utils/reportFormatters'

export interface KpiExportItem {
  label: string
  value: string
  change?: { value: string; direction: string }
}

export interface ActivityExportEntry {
  date: string
  description: string
  amount: string
}

export interface ReportExportInput {
  currency: string
  periodLabel: string
  kpis: KpiExportItem[]
  income: number
  expenses: number
  netCashFlow: number
  prevIncome: number
  prevExpenses: number
  prevSavings: number
  netWorth: number
  totalCash: number
  totalInvestments: number
  monthlyCashFlow: MonthlyTrend[]
  assetAllocation: AssetAllocation[]
  cashDistribution: { name: string; value: number }[]
  topExpenses: CategoryBreakdown[]
  topIncomes: CategoryBreakdown[]
  activityEntries: ActivityExportEntry[]
}

const FONT_SIZE_TITLE = 20
const FONT_SIZE_SUBTITLE = 10
const FONT_SIZE_SECTION = 13
const FONT_SIZE_BODY = 9
const PAGE_MARGIN = 20
const PAGE_WIDTH = 210
const CONTENT_WIDTH = PAGE_WIDTH - PAGE_MARGIN * 2
const COLORS = {
  primary: [41, 98, 255] as [number, number, number],
  secondary: [100, 116, 139] as [number, number, number],
  header: [248, 250, 252] as [number, number, number],
  border: [226, 232, 240] as [number, number, number],
}

function formatCurrencyRaw(value: number, currency: string): string {
  return `${currency} ${value.toLocaleString('en-US', { minimumFractionDigits: 0, maximumFractionDigits: 0 })}`
}

function drawFooter(doc: jsPDF, pageNum: number) {
  const totalPages = (doc as any).internal.pages.length - 1
  doc.setFontSize(8)
  doc.setTextColor(...COLORS.secondary)
  doc.text('Generated by InsAcc', PAGE_MARGIN, 290)
  doc.text(`Page ${pageNum} of ${totalPages}`, PAGE_WIDTH - PAGE_MARGIN, 290, { align: 'right' })
}

function checkPageBreak(doc: jsPDF, y: number, needed: number): number {
  if (y + needed > 275) {
    drawFooter(doc, (doc as any).internal.getNumberOfPages())
    doc.addPage()
    return PAGE_MARGIN + 5
  }
  return y
}

// --- PDF ---

function generatePdf(data: ReportExportInput): ArrayBuffer {
  const doc = new jsPDF()
  const currency = data.currency
  let y = PAGE_MARGIN + 5
  let pageNum = 1

  // Title
  doc.setFontSize(FONT_SIZE_TITLE)
  doc.setTextColor(...COLORS.primary)
  doc.text('InsAcc Financial Report', PAGE_MARGIN, y)
  y += 8

  // Timestamp & period
  doc.setFontSize(FONT_SIZE_SUBTITLE)
  doc.setTextColor(...COLORS.secondary)
  const now = new Date()
  const dateStr = now.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
  doc.text(`Generated: ${dateStr}`, PAGE_MARGIN, y)
  y += 5
  doc.text(`Period: ${data.periodLabel}`, PAGE_MARGIN, y)
  y += 10

  // Separator line
  doc.setDrawColor(...COLORS.border)
  doc.line(PAGE_MARGIN, y, PAGE_WIDTH - PAGE_MARGIN, y)
  y += 8

  // --- KPI Summary ---
  y = checkPageBreak(doc, y, 50)
  doc.setFontSize(FONT_SIZE_SECTION)
  doc.setTextColor(...COLORS.primary)
  doc.text('KPI Summary', PAGE_MARGIN, y)
  y += 6

  const kpiRows = data.kpis.map(k => [
    k.label,
    k.value,
    k.change ? k.change.value : '-',
  ])
autoTable(doc, {
    head: [['Metric', 'Value', 'Change']],
    body: kpiRows,
    startY: y,
    theme: 'striped',
    headStyles: { fillColor: COLORS.primary, fontSize: FONT_SIZE_BODY, fontStyle: 'bold' },
    bodyStyles: { fontSize: FONT_SIZE_BODY },
    columnStyles: { 0: { cellWidth: 50 }, 1: { cellWidth: 70 }, 2: { cellWidth: 40 } },
    margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
    styles: { halign: 'left' },
  })
  y = (doc as any).lastAutoTable.finalY + 8

  // --- Investment Growth Summary ---
  if (data.monthlyCashFlow.length > 0) {
    y = checkPageBreak(doc, y, 30)
    doc.setFontSize(FONT_SIZE_SECTION)
    doc.setTextColor(...COLORS.primary)
    doc.text('Investment Growth Summary', PAGE_MARGIN, y)
    y += 6

    doc.setFontSize(FONT_SIZE_BODY)
    doc.setTextColor(60, 60, 60)
    const totalInv = formatCurrencyRaw(data.totalInvestments, currency)
    const netWorth = formatCurrencyRaw(data.netWorth, currency)
    doc.text(`Total Investments: ${totalInv}`, PAGE_MARGIN, y)
    y += 5
    doc.text(`Net Worth: ${netWorth}`, PAGE_MARGIN, y)
    y += 5
    doc.text(`Cash: ${formatCurrencyRaw(data.totalCash, currency)}`, PAGE_MARGIN, y)
    y += 10
  }

  // --- Asset Allocation ---
  if (data.assetAllocation.length > 0) {
    y = checkPageBreak(doc, y, 20 + data.assetAllocation.length * 8)
    doc.setFontSize(FONT_SIZE_SECTION)
    doc.setTextColor(...COLORS.primary)
    doc.text('Asset Allocation', PAGE_MARGIN, y)
    y += 6

    const allocRows = data.assetAllocation.map(a => [
      a.type,
      formatCurrencyRaw(a.totalValue, currency),
      `${a.percentage.toFixed(1)}%`,
    ])
    autoTable(doc, {
      head: [['Type', 'Value', 'Allocation %']],
      body: allocRows,
      startY: y,
      theme: 'striped',
      headStyles: { fillColor: COLORS.primary, fontSize: FONT_SIZE_BODY, fontStyle: 'bold' },
      bodyStyles: { fontSize: FONT_SIZE_BODY },
      margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
    })
    y = (doc as any).lastAutoTable.finalY + 8
  }

  // --- Page break before cash flow ---
  y = checkPageBreak(doc, y, 20 + data.monthlyCashFlow.length * 8)

  // --- Cash Flow Summary ---
  if (data.monthlyCashFlow.length > 0) {
    doc.setFontSize(FONT_SIZE_SECTION)
    doc.setTextColor(...COLORS.primary)
    doc.text('Cash Flow Summary', PAGE_MARGIN, y)
    y += 6

    const cfRows = data.monthlyCashFlow.map(m => [
      formatMonth(m.month),
      formatCurrencyRaw(m.income, currency),
      formatCurrencyRaw(m.expense, currency),
      formatCurrencyRaw(m.net, currency),
    ])
    autoTable(doc, {
      head: [['Month', 'Income', 'Expenses', 'Net']],
      body: cfRows,
      startY: y,
      theme: 'striped',
      headStyles: { fillColor: COLORS.primary, fontSize: FONT_SIZE_BODY, fontStyle: 'bold' },
      bodyStyles: { fontSize: FONT_SIZE_BODY },
      margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
    })
    y = (doc as any).lastAutoTable.finalY + 8
  }

  // --- Cash Distribution ---
  if (data.cashDistribution.length > 0) {
    y = checkPageBreak(doc, y, 20 + data.cashDistribution.length * 8)
    doc.setFontSize(FONT_SIZE_SECTION)
    doc.setTextColor(...COLORS.primary)
    doc.text('Cash Distribution', PAGE_MARGIN, y)
    y += 6

    const cdRows = data.cashDistribution.map(cd => [
      cd.name,
      formatCurrencyRaw(cd.value, currency),
    ])
    autoTable(doc, {
      head: [['Account', 'Balance']],
      body: cdRows,
      startY: y,
      theme: 'striped',
      headStyles: { fillColor: COLORS.primary, fontSize: FONT_SIZE_BODY, fontStyle: 'bold' },
      bodyStyles: { fontSize: FONT_SIZE_BODY },
      margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
    })
    y = (doc as any).lastAutoTable.finalY + 8
  }

  // --- Top Income Categories ---
  if (data.topIncomes.length > 0) {
    y = checkPageBreak(doc, y, 20 + data.topIncomes.length * 8)
    doc.setFontSize(FONT_SIZE_SECTION)
    doc.setTextColor(...COLORS.primary)
    doc.text('Top Income Categories', PAGE_MARGIN, y)
    y += 6

    const incRows = data.topIncomes.map(i => [
      i.category,
      formatCurrencyRaw(i.amount, currency),
      `${i.percentage.toFixed(1)}%`,
    ])
    autoTable(doc, {
      head: [['Category', 'Amount', '%']],
      body: incRows,
      startY: y,
      theme: 'striped',
      headStyles: { fillColor: COLORS.primary, fontSize: FONT_SIZE_BODY, fontStyle: 'bold' },
      bodyStyles: { fontSize: FONT_SIZE_BODY },
      margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
    })
    y = (doc as any).lastAutoTable.finalY + 8
  }

  // --- Top Expense Categories ---
  if (data.topExpenses.length > 0) {
    y = checkPageBreak(doc, y, 20 + data.topExpenses.length * 8)
    doc.setFontSize(FONT_SIZE_SECTION)
    doc.setTextColor(...COLORS.primary)
    doc.text('Top Expense Categories', PAGE_MARGIN, y)
    y += 6

    const expRows = data.topExpenses.map(e => [
      e.category,
      formatCurrencyRaw(e.amount, currency),
      `${e.percentage.toFixed(1)}%`,
    ])
    autoTable(doc, {
      head: [['Category', 'Amount', '%']],
      body: expRows,
      startY: y,
      theme: 'striped',
      headStyles: { fillColor: COLORS.primary, fontSize: FONT_SIZE_BODY, fontStyle: 'bold' },
      bodyStyles: { fontSize: FONT_SIZE_BODY },
      margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
    })
    y = (doc as any).lastAutoTable.finalY + 8
  }

  // --- Recent Activity ---
  if (data.activityEntries.length > 0) {
    y = checkPageBreak(doc, y, 20 + data.activityEntries.length * 6)
    doc.setFontSize(FONT_SIZE_SECTION)
    doc.setTextColor(...COLORS.primary)
    doc.text('Recent Activity', PAGE_MARGIN, y)
    y += 6

    doc.setFontSize(FONT_SIZE_BODY)
    doc.setTextColor(60, 60, 60)
    for (const act of data.activityEntries) {
      y = checkPageBreak(doc, y, 6)
      doc.text(`• ${act.date} — ${act.description} — ${act.amount}`, PAGE_MARGIN, y)
      y += 5
    }
    y += 4
  }

  // Footer on last page
  const totalPages = (doc as any).internal.pages.length - 1
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i)
    drawFooter(doc, i)
  }

  return doc.output('arraybuffer')
}

// --- Excel ---

function generateExcel(data: ReportExportInput): Uint8Array {
  const wb = XLSX.utils.book_new()
  const currency = data.currency

  const numFmt = '#,##0'

  // Summary sheet
  const summaryData = [
    ['InsAcc Financial Report', ''],
    ['Generated', new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })],
    ['Period', data.periodLabel],
    ['', ''],
    ['KPI Summary', ''],
    ['Metric', 'Value'],
    ...data.kpis.map(k => [k.label, k.value]),
    ['', ''],
    ['Totals', ''],
    ['Net Worth', data.netWorth],
    ['Total Cash', data.totalCash],
    ['Total Investments', data.totalInvestments],
    ['Income', data.income],
    ['Expenses', data.expenses],
    ['Net Cash Flow', data.netCashFlow],
  ]
  const wsSummary = XLSX.utils.aoa_to_sheet(summaryData)
  wsSummary['!cols'] = [{ wch: 25 }, { wch: 20 }]
  // Currency format for numeric cells
  for (let r = 12; r <= 17; r++) {
    const ref = XLSX.utils.encode_cell({ r, c: 1 })
    if (wsSummary[ref] && typeof wsSummary[ref].v === 'number') {
      wsSummary[ref].z = numFmt
    }
  }
  XLSX.utils.book_append_sheet(wb, wsSummary, 'Summary')

  // KPIs sheet
  const kpiData = [
    ['Metric', 'Value', 'Change'],
    ...data.kpis.map(k => [k.label, k.value, k.change ? k.change.value : '']),
  ]
  const wsKpi = XLSX.utils.aoa_to_sheet(kpiData)
  wsKpi['!cols'] = [{ wch: 20 }, { wch: 20 }, { wch: 15 }]
  XLSX.utils.book_append_sheet(wb, wsKpi, 'KPIs')

  // Cash Flow sheet
  if (data.monthlyCashFlow.length > 0) {
    const cfData = [
      ['Month', 'Income', 'Expenses', 'Net'],
      ...data.monthlyCashFlow.map(m => [formatMonth(m.month), m.income, m.expense, m.net]),
    ]
    const wsCf = XLSX.utils.aoa_to_sheet(cfData)
    wsCf['!cols'] = [{ wch: 18 }, { wch: 15 }, { wch: 15 }, { wch: 15 }]
    for (let r = 1; r <= data.monthlyCashFlow.length; r++) {
      for (let c = 1; c <= 3; c++) {
        const ref = XLSX.utils.encode_cell({ r, c })
        if (wsCf[ref] && typeof wsCf[ref].v === 'number') {
          wsCf[ref].z = numFmt
        }
      }
    }
    XLSX.utils.book_append_sheet(wb, wsCf, 'Cash Flow')
  }

  // Asset Allocation sheet
  if (data.assetAllocation.length > 0) {
    const allocData = [
      ['Type', 'Value', 'Allocation %'],
      ...data.assetAllocation.map(a => [a.type, a.totalValue, a.percentage]),
    ]
    const wsAlloc = XLSX.utils.aoa_to_sheet(allocData)
    wsAlloc['!cols'] = [{ wch: 20 }, { wch: 15 }, { wch: 12 }]
    for (let r = 1; r <= data.assetAllocation.length; r++) {
      const ref = XLSX.utils.encode_cell({ r, c: 1 })
      if (wsAlloc[ref] && typeof wsAlloc[ref].v === 'number') {
        wsAlloc[ref].z = numFmt
      }
    }
    XLSX.utils.book_append_sheet(wb, wsAlloc, 'Asset Allocation')
  }

  // Income sheet
  if (data.topIncomes.length > 0) {
    const incData = [
      ['Category', 'Amount', '%'],
      ...data.topIncomes.map(i => [i.category, i.amount, i.percentage]),
    ]
    const wsInc = XLSX.utils.aoa_to_sheet(incData)
    wsInc['!cols'] = [{ wch: 20 }, { wch: 15 }, { wch: 10 }]
    for (let r = 1; r <= data.topIncomes.length; r++) {
      const ref = XLSX.utils.encode_cell({ r, c: 1 })
      if (wsInc[ref] && typeof wsInc[ref].v === 'number') {
        wsInc[ref].z = numFmt
      }
    }
    XLSX.utils.book_append_sheet(wb, wsInc, 'Income')
  }

  // Expenses sheet
  if (data.topExpenses.length > 0) {
    const expData = [
      ['Category', 'Amount', '%'],
      ...data.topExpenses.map(e => [e.category, e.amount, e.percentage]),
    ]
    const wsExp = XLSX.utils.aoa_to_sheet(expData)
    wsExp['!cols'] = [{ wch: 20 }, { wch: 15 }, { wch: 10 }]
    for (let r = 1; r <= data.topExpenses.length; r++) {
      const ref = XLSX.utils.encode_cell({ r, c: 1 })
      if (wsExp[ref] && typeof wsExp[ref].v === 'number') {
        wsExp[ref].z = numFmt
      }
    }
    XLSX.utils.book_append_sheet(wb, wsExp, 'Expenses')
  }

  // Activity sheet
  if (data.activityEntries.length > 0) {
    const actData = [
      ['Date', 'Description', 'Amount'],
      ...data.activityEntries.map(a => [a.date, a.description, a.amount]),
    ]
    const wsAct = XLSX.utils.aoa_to_sheet(actData)
    wsAct['!cols'] = [{ wch: 14 }, { wch: 40 }, { wch: 18 }]
    XLSX.utils.book_append_sheet(wb, wsAct, 'Activity')
  }

  return XLSX.write(wb, { type: 'array', bookType: 'xlsx' })
}

// --- CSV ---

function generateCsv(data: ReportExportInput): string {
  const lines: string[] = []
  const esc = (v: string | number) => {
    const s = String(v)
    if (s.includes(',') || s.includes('"') || s.includes('\n')) {
      return `"${s.replace(/"/g, '""')}"`
    }
    return s
  }

  lines.push('InsAcc Financial Report')
  lines.push(`Generated,${esc(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }))}`)
  lines.push(`Period,${esc(data.periodLabel)}`)
  lines.push('')

  lines.push('KPI Summary')
  lines.push('Metric,Value,Change')
  for (const k of data.kpis) {
    lines.push(`${esc(k.label)},${esc(k.value)},${esc(k.change ? k.change.value : '')}`)
  }
  lines.push('')

  if (data.monthlyCashFlow.length > 0) {
    lines.push('Cash Flow')
    lines.push('Month,Income,Expenses,Net')
    for (const m of data.monthlyCashFlow) {
      lines.push(`${esc(formatMonth(m.month))},${m.income},${m.expense},${m.net}`)
    }
    lines.push('')
  }

  if (data.assetAllocation.length > 0) {
    lines.push('Asset Allocation')
    lines.push('Type,Value,Allocation %')
    for (const a of data.assetAllocation) {
      lines.push(`${esc(a.type)},${a.totalValue},${a.percentage}`)
    }
    lines.push('')
  }

  if (data.cashDistribution.length > 0) {
    lines.push('Cash Distribution')
    lines.push('Account,Balance')
    for (const cd of data.cashDistribution) {
      lines.push(`${esc(cd.name)},${cd.value}`)
    }
    lines.push('')
  }

  if (data.topIncomes.length > 0) {
    lines.push('Top Income Categories')
    lines.push('Category,Amount,%')
    for (const i of data.topIncomes) {
      lines.push(`${esc(i.category)},${i.amount},${i.percentage}`)
    }
    lines.push('')
  }

  if (data.topExpenses.length > 0) {
    lines.push('Top Expense Categories')
    lines.push('Category,Amount,%')
    for (const e of data.topExpenses) {
      lines.push(`${esc(e.category)},${e.amount},${e.percentage}`)
    }
    lines.push('')
  }

  if (data.activityEntries.length > 0) {
    lines.push('Recent Activity')
    lines.push('Date,Description,Amount')
    for (const a of data.activityEntries) {
      lines.push(`${esc(a.date)},${esc(a.description)},${esc(a.amount)}`)
    }
    lines.push('')
  }

  return lines.join('\n')
}

// --- Public API ---

export async function exportReport(
  format: 'pdf' | 'csv' | 'excel',
  data: ReportExportInput,
): Promise<string | null> {
  switch (format) {
    case 'pdf': {
      let buf: ArrayBuffer
      try {
        buf = generatePdf(data)
      } catch (e) {
        throw new Error(`PDF generation failed: ${(e as Error).message}`)
      }
      return saveWithDialog('Financial_Report.pdf', [{ name: 'PDF', extensions: ['pdf'] }], buf)
    }
    case 'excel': {
      let buf: Uint8Array
      try {
        buf = generateExcel(data)
      } catch (e) {
        throw new Error(`Excel generation failed: ${(e as Error).message}`)
      }
      return saveWithDialog('Financial_Report.xlsx', [{ name: 'Excel', extensions: ['xlsx'] }], buf)
    }
    case 'csv': {
      let content: string
      try {
        content = generateCsv(data)
      } catch (e) {
        throw new Error(`CSV generation failed: ${(e as Error).message}`)
      }
      return saveWithDialog('Financial_Report.csv', [{ name: 'CSV', extensions: ['csv'] }], content)
    }
  }
}

export { generatePdf, generateExcel, generateCsv }
