import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import * as XLSX from 'xlsx-js-style'
import { saveWithDialog } from './exportService'
import type { MonthlyTrend, AssetAllocation, CategoryBreakdown } from '../data/reports'
import { formatMonth } from '../utils/reportFormatters'
import { formatDate } from '../utils'
import type { Account, Voucher } from '../accounting/types'

export interface KpiExportItem {
  label: string
  value: string
  change?: { value: string; direction: string }
}

export interface ActivityExportEntry {
  date: string
  description: string
  amount: string
}

export interface ReportExportInput {
  currency: string
  periodLabel: string
  moduleName?: string
  kpis: KpiExportItem[]
  income: number
  expenses: number
  netCashFlow: number
  prevIncome: number
  prevExpenses: number
  prevSavings: number
  netWorth: number
  totalCash: number
  totalInvestments: number
  monthlyCashFlow: MonthlyTrend[]
  assetAllocation: AssetAllocation[]
  cashDistribution: { name: string; value: number }[]
  topExpenses: CategoryBreakdown[]
  topIncomes: CategoryBreakdown[]
  activityEntries: ActivityExportEntry[]
}

const FONT_SIZE_TITLE = 20
const FONT_SIZE_SUBTITLE = 10
const FONT_SIZE_SECTION = 13
const FONT_SIZE_BODY = 9
const PAGE_MARGIN = 20

export function getThemeColorArray(): [number, number, number] {
  if (typeof document !== 'undefined') {
    const appShell = document.querySelector('.app-shell')
    if (appShell && appShell.getAttribute('data-module') === 'property') {
      return [222, 141, 169]
    }
  }
  return [15, 76, 53]
}

const PAGE_WIDTH = 210
const COLORS = new Proxy({
  secondary: [100, 116, 139] as [number, number, number],
  header: [248, 251, 249] as [number, number, number],
  border: [226, 232, 240] as [number, number, number],
}, {
  get: (target, prop) => {
    if (prop === 'primary') return getThemeColorArray();
    return target[prop];
  }
}) as any;

function formatCurrencyRaw(value: number, currency: string): string {
  return `${currency} ${value.toLocaleString('en-US', { minimumFractionDigits: 0, maximumFractionDigits: 0 })}`
}

function drawFooter(doc: jsPDF, pageNum: number) {
  const totalPages = (doc as any).internal.pages.length - 1
  doc.setFontSize(8)
  doc.setTextColor(...COLORS.secondary)
  doc.text('Generated by InsAcc', PAGE_MARGIN, 290)
  doc.text(`Page ${pageNum} of ${totalPages}`, PAGE_WIDTH - PAGE_MARGIN, 290, { align: 'right' })
}

function checkPageBreak(doc: jsPDF, y: number, needed: number): number {
  if (y + needed > 275) {
    drawFooter(doc, (doc as any).internal.getNumberOfPages())
    doc.addPage()
    return PAGE_MARGIN + 5
  }
  return y
}

function roundDecimals(val: any): any {
  if (typeof val === 'number' && !Number.isInteger(val)) {
    return Number(val.toFixed(2))
  }
  return val
}

function formatRows(rows: any[][]): any[][] {
  return rows.map(r => r.map(roundDecimals))
}


function generatePdf(data: ReportExportInput): ArrayBuffer {
  const doc = new jsPDF()
  const currency = data.currency
  let y = PAGE_MARGIN + 5

  doc.setFontSize(FONT_SIZE_TITLE)
  doc.setTextColor(...COLORS.primary)
  doc.text('InsAcc Financial Report', PAGE_MARGIN, y)
  y += 8

  doc.setFontSize(FONT_SIZE_SUBTITLE)
  doc.setTextColor(...COLORS.secondary)
  const now = new Date()
  doc.text(`Generated: ${now.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, PAGE_MARGIN, y)
  y += 5
  doc.text(`Period: ${data.periodLabel}`, PAGE_MARGIN, y)
  y += 10

  doc.setDrawColor(...COLORS.border)
  doc.line(PAGE_MARGIN, y, PAGE_WIDTH - PAGE_MARGIN, y)
  y += 8

  y = checkPageBreak(doc, y, 50)
  doc.setFontSize(FONT_SIZE_SECTION)
  doc.setTextColor(...COLORS.primary)
  doc.text('KPI Summary', PAGE_MARGIN, y)
  y += 6

  autoTable(doc, {
    head: [['Metric', 'Value', 'Change']],
    body: data.kpis.map(k => [k.label, k.value, k.change ? k.change.value : '-']),
    startY: y,
    theme: 'striped',
    headStyles: { fillColor: COLORS.primary, fontSize: FONT_SIZE_BODY, fontStyle: 'bold' },
    bodyStyles: { fontSize: FONT_SIZE_BODY },
    margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
    styles: { halign: 'left' },
  })
  y = (doc as any).lastAutoTable.finalY + 8

  const totalPages = (doc as any).internal.pages.length - 1
  for (let i = 1; i <= totalPages; i++) { doc.setPage(i); drawFooter(doc, i) }
  return doc.output('arraybuffer')
}

function generateCsv(data: ReportExportInput): string {
  data.kpis.forEach(k => { if (typeof k.value === 'number') k.value = roundDecimals(k.value) })
  const lines: string[] = []
  const esc = (v: string | number | undefined | null) => {
    if (v === null || v === undefined) return ''
    const s = String(v)
    if (/^\d{2}\/\d{2}\/\d{4}$/.test(s)) return `="${s}"`
    return (s.includes(',') || s.includes('"') || s.includes('\n')) ? `"${s.replace(/"/g, '""')}"` : s
  }
  if (data.moduleName) lines.push(esc(data.moduleName))
  lines.push('InsAcc Financial Report')
  lines.push(`Generated,${esc(new Date().toLocaleDateString())}`)
  lines.push(`Period,${esc(data.periodLabel)}`)
  lines.push('')
  lines.push('KPI Summary')
  lines.push('Metric,Value,Change')
  for (const k of data.kpis) lines.push(`${esc(k.label)},${esc(k.value)},${esc(k.change ? k.change.value : '')}`)
  return '\uFEFF' + lines.join('\n')
}

function generateExcel(data: ReportExportInput): Uint8Array {
  data.kpis.forEach(k => { if (typeof k.value === 'number') k.value = roundDecimals(k.value) })
  const wb = XLSX.utils.book_new()
  const summaryData = [
    ...(data.moduleName ? [[data.moduleName, '']] : []),
    ['InsAcc Financial Report', ''],
    ['Generated', new Date().toLocaleDateString()],
    ['Period', data.periodLabel],
    ['', ''],
    ['Metric', 'Value'],
    ...data.kpis.map(k => [k.label, k.value]),
  ]
  const ws = XLSX.utils.aoa_to_sheet(summaryData)
  ws['!cols'] = [{ wch: 25 }, { wch: 20 }]
  XLSX.utils.book_append_sheet(wb, ws, 'Summary')
  return XLSX.write(wb, { type: 'array', bookType: 'xlsx' })
}

export async function exportReport(
  format: 'pdf' | 'csv' | 'excel',
  data: ReportExportInput,
): Promise<string | null> {
  switch (format) {
    case 'pdf': {
      const buf = generatePdf(data)
      return saveWithDialog('Financial_Report.pdf', [{ name: 'PDF', extensions: ['pdf'] }], buf)
    }
    case 'excel': {
      const buf = generateExcel(data)
      return saveWithDialog('Financial_Report.xlsx', [{ name: 'Excel', extensions: ['xlsx'] }], buf)
    }
    case 'csv': {
      const content = generateCsv(data)
      return saveWithDialog('Financial_Report.csv', [{ name: 'CSV', extensions: ['csv'] }], content)
    }
  }
}


// ════════════════════════════════════════════════════════════════════
// PREMIUM ACCOUNTING EXCEL EXPORT  –  8-Sheet Professional Workbook
// Inspired by: Zoho Books / QuickBooks / Xero / Oracle NetSuite
// ════════════════════════════════════════════════════════════════════

export interface ExcelExportParams {
  companyName: string
  reportTitle: string
  module: 'Investment' | 'Property'
  periodLabel: string
  generatedBy: string
  currency: string
  accounts: Account[]
  vouchers: Voucher[]
  auditLogs?: any[]
  reportType?: 'Standard' | 'LedgerBreakup' | 'PropertyBreakup' | 'SupplierBreakup' | 'TenantBreakup'
  filters?: {
    dateRange?: { start: string; end: string }
    bankAccountId?: string
    accountId?: string
    assetName?: string
    buildingName?: string
    tenantName?: string
    voucherType?: string
    status?: string
    buyerName?: string
    vendorName?: string
  }
  properties?: any[]
  units?: any[]
  tenants?: any[]
  leases?: any[]
  investments?: any[]
  advancedOptions?: any
}

// ── Colour palette (ARGB hex for xlsx-js-style) ───────────────────
const C = new Proxy({}, {
  get: (target, prop) => {
    let mod = undefined
    if (typeof document !== 'undefined') {
      const appShell = document.querySelector('.app-shell')
      if (appShell) mod = appShell.getAttribute('data-module') || undefined
    }
    const isProp = mod && mod.toLowerCase().includes('propert')
    
    const colors = isProp ? {
      primaryDark:  'D07D9B',
      primary:      'DE8DA9',
      primaryMid:   'E49DB6',
      primaryLight: 'F4E6EB',
      gold:         'D4AF37',
      red:          'EF4444',
      white:        'FFFFFF',
      black:        '1A2230',
      gray:         '64748B',
      grayLight:    'F1F5F9',
      grayBorder:   'CBD5E1',
      rowAlt:       'FDF7F9',
      rowEven:      'FFFFFF',
      totalsRow:    'FAEDF1',
      subHdr:       'B05D7C',
    } : {
      primaryDark:  '0F4C35',
      primary:      '22A45D',
      primaryMid:   '1A7A47',
      primaryLight: 'D6F0E1',
      gold:         'D4AF37',
      red:          'EF4444',
      white:        'FFFFFF',
      black:        '1A2230',
      gray:         '64748B',
      grayLight:    'F1F5F9',
      grayBorder:   'CBD5E1',
      rowAlt:       'F8FBF9',
      rowEven:      'FFFFFF',
      totalsRow:    'E8F5ED',
      subHdr:       '1E3A2F',
    };
    return colors[prop];
  }
}) as any;

const FN = 'Calibri'

type XCell = { v: string | number; t: 's' | 'n'; z?: string; s?: any }

function bdr(color = C.grayBorder, style = 'thin') {
  return { style, color: { rgb: color } }
}
const allBdr = { top: bdr(), bottom: bdr(), left: bdr(), right: bdr() }

function mkCell(value: string | number, s: any = {}, fmt?: string): XCell {
  const t = typeof value === 'number' ? 'n' : 's'
  const c: XCell = { v: value, t }
  if (fmt) c.z = fmt
  if (Object.keys(s).length) c.s = s
  return c
}

function hCell(text: string, opts: { sz?: number; bold?: boolean; bg?: string; fg?: string; center?: boolean; italic?: boolean } = {}): XCell {
  return mkCell(text, {
    font: { name: FN, bold: opts.bold !== false, sz: opts.sz ?? 10, italic: opts.italic ?? false, color: { rgb: opts.fg ?? C.white } },
    fill: { fgColor: { rgb: opts.bg ?? C.primaryDark } },
    alignment: { horizontal: opts.center ? 'center' : 'left', vertical: 'center', wrapText: false },
    border: allBdr,
  })
}

function dCell(value: string | number, opts: { bold?: boolean; italic?: boolean; color?: string; bg?: string; center?: boolean; right?: boolean; fmt?: string } = {}): XCell {
  const s: any = {
    font: { name: FN, sz: 10, bold: opts.bold ?? false, italic: opts.italic ?? false, color: { rgb: opts.color ?? C.black } },
    alignment: { horizontal: opts.right ? 'right' : (opts.center ? 'center' : 'left'), vertical: 'center' },
    border: allBdr,
  }
  if (opts.bg) s.fill = { fgColor: { rgb: opts.bg } }
  return mkCell(value, s, opts.fmt)
}

function cCell(value: number, bg?: string, bold?: boolean): XCell {
  return dCell(value, { right: true, bold: bold ?? false, color: value < 0 ? C.red : C.black, bg, fmt: '"AED" #,##0.00' })
}

function eCell(bg?: string): XCell {
  const s: any = { font: { name: FN, sz: 10 }, border: allBdr }
  if (bg) s.fill = { fgColor: { rgb: bg } }
  return mkCell('', s)
}

function sectionRow(text: string, cols: number, bg = C.subHdr): XCell[] {
  return Array.from({ length: cols }, (_, i) =>
    i === 0
      ? mkCell(text, { font: { name: FN, bold: true, sz: 10, color: { rgb: C.white } }, fill: { fgColor: { rgb: bg } }, alignment: { horizontal: 'left', vertical: 'center' }, border: allBdr })
      : mkCell('', { fill: { fgColor: { rgb: bg } }, border: allBdr })
  )
}

function fmtD(d: string): string {
  return formatDate(d, 'DD/MM/YYYY')
}

function fmtDT(d: string | Date): string {
  try {
    const dt = typeof d === 'string' ? new Date(d) : d
    return dt.toLocaleString('en-GB', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' })
  } catch { return String(d) }
}

function autoW(rows: XCell[][]): { wch: number }[] {
  const w: number[] = []
  for (const row of rows) {
    row.forEach((c, i) => {
      const l = c && c.v !== undefined ? String(c.v).length : 8
      w[i] = Math.min(60, Math.max(w[i] ?? 8, l + 3))
    })
  }
  return w.map(n => ({ wch: n }))
}

function buildWS(rows: XCell[][], opts: { freeze?: { r: number; c: number }; filterRow?: number; colW?: { wch: number }[]; landscape?: boolean; merges?: any[]; rowHeights?: any[] } = {}): any {
  const ws: any = {}
  let maxC = 0
  rows.forEach((row, r) => {
    row.forEach((c, col) => {
      if (!c) return
      ws[XLSX.utils.encode_cell({ r, c: col })] = c
      if (col > maxC) maxC = col
    })
  })
  ws['!ref'] = XLSX.utils.encode_range({ s: { r: 0, c: 0 }, e: { r: rows.length - 1, c: maxC } })
  if (opts.freeze) {
    ws['!views'] = [{ state: 'frozen', xSplit: opts.freeze.c, ySplit: opts.freeze.r, topLeftCell: XLSX.utils.encode_cell({ r: opts.freeze.r, c: opts.freeze.c }), activePane: 'bottomLeft' }]
  }
  if (opts.filterRow !== undefined) {
    const fCols = rows[opts.filterRow]?.length ?? maxC + 1
    ws['!autofilter'] = { ref: `${XLSX.utils.encode_cell({ r: opts.filterRow, c: 0 })}:${XLSX.utils.encode_cell({ r: opts.filterRow, c: fCols - 1 })}` }
  }
  ws['!cols'] = opts.colW ?? autoW(rows)
  ws['!pageSetup'] = { orientation: opts.landscape === false ? 'portrait' : 'landscape', paperSize: 9, fitToPage: true, fitToWidth: 1, fitToHeight: 0 }
  ws['!margins'] = { left: 0.5, right: 0.5, top: 0.75, bottom: 0.75, header: 0.4, footer: 0.4 }
  if (opts.merges) ws['!merges'] = opts.merges
  if (opts.rowHeights) ws['!rows'] = opts.rowHeights
  return ws
}

// ── SHEET 1: COVER ────────────────────────────────────────────────
function getCoverData(p: ExcelExportParams, count: number, colCount: number): any {
  const now = new Date()
  const rows: XCell[][] = []
  const bg = C.white
  const blk = () => Array(colCount).fill(null).map(() => mkCell('', { fill: { fgColor: { rgb: bg } } }))
  const cvr = (text: string, sz: number, bold: boolean, fg = C.black, filBg = bg) =>
    Array(colCount).fill(null).map((_, i) => mkCell(i === 0 ? text : '', {
      font: { name: FN, bold, sz, color: { rgb: fg } },
      fill: { fgColor: { rgb: filBg } },
      alignment: { horizontal: 'center', vertical: 'center' },
    }))
  const metaBg = 'FAFAFA'
  
  const lblSpan = Math.floor(colCount / 2)
  
  const meta = (lbl: string, val: string) => {
    const row = Array(colCount).fill(null).map(() => mkCell('', { fill: { fgColor: { rgb: metaBg } } }))
    row[0] = mkCell(lbl, { font: { name: FN, bold: true, sz: 10, color: { rgb: C.gray } }, fill: { fgColor: { rgb: metaBg } }, alignment: { horizontal: 'right', vertical: 'center' }, border: { right: bdr(C.grayBorder) } })
    row[lblSpan] = mkCell(val, { font: { name: FN, sz: 11, color: { rgb: C.black } }, fill: { fgColor: { rgb: metaBg } }, alignment: { horizontal: 'left', vertical: 'center' } })
    return row
  }
  const blkM = () => Array(colCount).fill(null).map(() => mkCell('', { fill: { fgColor: { rgb: metaBg } } }))

  rows.push(blk())
  rows.push(cvr('Sameer Ishaq Harmoudi', 14, true, C.black))
  rows.push(cvr('INSACC', 24, true, C.black))
  rows.push(cvr('Intelligent Asset & Investment Accounting', 10, false, C.gray))
  rows.push(blk())
  rows.push(cvr(p.reportTitle, 16, true, C.black))
  rows.push(cvr(p.module === 'Property' ? 'Properties Management' : 'Investment', 11, false, C.gray))
  rows.push(blk())
  rows.push(blkM())
  rows.push(meta('Reporting Period', p.periodLabel))
  rows.push(blkM())
  rows.push(meta('Currency', p.currency))
  rows.push(meta('Generated By', p.generatedBy))
  rows.push(meta('Generated On', fmtDT(now)))
  rows.push(blkM())
  rows.push(meta('Total Transactions', String(count)))
  rows.push(blkM())
  rows.push(meta('', 'Generated by InsAcc — Intelligent Asset & Investment Accounting'))

  return {
    rows,
    merges: [
      { s: { r: 3, c: 0 }, e: { r: 3, c: colCount - 1 } },
      { s: { r: 5, c: 0 }, e: { r: 5, c: colCount - 1 } },
      { s: { r: 6, c: 0 }, e: { r: 6, c: colCount - 1 } },
      { s: { r: 9, c: 0 }, e: { r: 9, c: colCount - 1 } },
      { s: { r: 11, c: 0 }, e: { r: 11, c: colCount - 1 } },
      { s: { r: 14, c: 0 }, e: { r: 14, c: lblSpan - 1 } }, { s: { r: 14, c: lblSpan }, e: { r: 14, c: colCount - 1 } },
      { s: { r: 16, c: 0 }, e: { r: 16, c: lblSpan - 1 } }, { s: { r: 16, c: lblSpan }, e: { r: 16, c: colCount - 1 } },
      { s: { r: 17, c: 0 }, e: { r: 17, c: lblSpan - 1 } }, { s: { r: 17, c: lblSpan }, e: { r: 17, c: colCount - 1 } },
      { s: { r: 18, c: 0 }, e: { r: 18, c: lblSpan - 1 } }, { s: { r: 18, c: lblSpan }, e: { r: 18, c: colCount - 1 } },
      { s: { r: 20, c: 0 }, e: { r: 20, c: lblSpan - 1 } }, { s: { r: 20, c: lblSpan }, e: { r: 20, c: colCount - 1 } },
      { s: { r: 22, c: 0 }, e: { r: 22, c: lblSpan - 1 } }, { s: { r: 22, c: lblSpan }, e: { r: 22, c: colCount - 1 } },
    ],
    rowHeights: [
      {}, {}, {}, { hpt: 52 }, { hpt: 10 }, { hpt: 22 }, { hpt: 10 },
      { hpt: 6 }, { hpt: 10 }, { hpt: 38 }, { hpt: 10 }, { hpt: 22 },
    ]
  }
}

// ── SHEET 2: EXECUTIVE SUMMARY ────────────────────────────────────
function sheetSummary(p: ExcelExportParams, fv: Voucher[], totDr: number, totCr: number, coverData?: any): any {
  const rows: XCell[][] = []

  if (coverData) {
    rows.push(...coverData.rows, [], [])
  }

  rows.push([hCell('EXECUTIVE SUMMARY', { sz: 13, bg: C.primaryDark }), hCell('', { bg: C.primaryDark }), hCell('', { bg: C.primaryDark }), hCell('', { bg: C.primaryDark })])
  rows.push([hCell(p.reportTitle, { sz: 10, bg: C.subHdr, bold: false }), hCell('', { bg: C.subHdr }), hCell('', { bg: C.subHdr }), hCell('', { bg: C.subHdr })])
  rows.push([hCell(`Period: ${p.periodLabel || 'All Time'}`, { sz: 10, bg: C.subHdr, bold: false }), hCell('', { bg: C.subHdr }), hCell('', { bg: C.subHdr }), hCell('', { bg: C.subHdr })])
  rows.push([])

  rows.push(sectionRow('  KEY PERFORMANCE INDICATORS', 4))
  rows.push([hCell('Metric', { bg: C.primary }), hCell('Value', { bg: C.primary }), hCell('Notes', { bg: C.primary }), hCell('', { bg: C.primary })])

  let incTot = 0, expTot = 0
  for (const v of fv) {
    for (const l of v.lines) {
      const a = p.accounts.find(x => x.id === l.accountId)
      if (!a) continue
      if (a.type === 'revenue' && l.type === 'Credit') incTot += l.amount
      if (a.type === 'expense' && l.type === 'Debit') expTot += l.amount
    }
  }

  const kpis: [string, string | number, string][] = [
    ['Total Vouchers', fv.length, `Period: ${p.periodLabel}`],
    ['Total Debit', totDr, 'Sum of all debit entries'],
    ['Total Credit', totCr, 'Sum of all credit entries'],
    ['Net Movement', totDr - totCr, 'Debit minus Credit'],
    ['Total Income', incTot, 'Revenue account credits'],
    ['Total Expenses', expTot, 'Expense account debits'],
    ['Net Profit / (Loss)', incTot - expTot, 'Income minus Expenses'],
  ]

  kpis.forEach(([lbl, val, note], idx) => {
    const bg = idx % 2 === 0 ? C.rowEven : C.rowAlt
    rows.push([
      dCell(lbl, { bg, bold: true }),
      typeof val === 'number' 
        ? (lbl === 'Total Vouchers' ? dCell(val, { bg, right: true, bold: true, fmt: '#,##0' }) : cCell(val, bg))
        : dCell(val, { bg, bold: true, color: C.primaryMid }),
      dCell(note, { bg, italic: true, color: C.gray }),
      eCell(bg),
    ])
  })
  rows.push([])

  // Monthly breakdown
  const months: Record<string, { inc: number; exp: number; cnt: number }> = {}
  for (const v of fv) {
    const m = v.date.slice(0, 7)
    if (!months[m]) months[m] = { inc: 0, exp: 0, cnt: 0 }
    months[m].cnt++
    for (const l of v.lines) {
      const a = p.accounts.find(x => x.id === l.accountId)
      if (!a) continue
      if (a.type === 'revenue' && l.type === 'Credit') months[m].inc += l.amount
      if (a.type === 'expense' && l.type === 'Debit') months[m].exp += l.amount
    }
  }
  const mKeys = Object.keys(months).sort()
  if (mKeys.length > 0) {
    rows.push(sectionRow('  MONTHLY BREAKDOWN', 5))
    rows.push([hCell('Month', { bg: C.primary }), hCell('Transactions', { bg: C.primary, center: true }), hCell('Income', { bg: C.primary }), hCell('Expenses', { bg: C.primary }), hCell('Net', { bg: C.primary })])
    mKeys.forEach((m, i) => {
      const bg = i % 2 === 0 ? C.rowEven : C.rowAlt
      const { inc, exp, cnt } = months[m]
      rows.push([dCell(formatMonth(m), { bg, bold: true }), dCell(cnt, { bg, center: true }), cCell(inc, bg), cCell(exp, bg), cCell(inc - exp, bg)])
    })
    const tI = mKeys.reduce((s, m) => s + months[m].inc, 0)
    const tE = mKeys.reduce((s, m) => s + months[m].exp, 0)
    rows.push([dCell('TOTAL', { bold: true, bg: C.totalsRow }), dCell(fv.length, { bold: true, bg: C.totalsRow, center: true }), cCell(tI, C.totalsRow, true), cCell(tE, C.totalsRow, true), cCell(tI - tE, C.totalsRow, true)])
    rows.push([])
  }

  const offset = coverData ? coverData.rows.length + 2 : 0

  return buildWS(rows, { 
    freeze: { r: 1 + offset, c: 0 }, 
    colW: [{ wch: 30 }, { wch: 18 }, { wch: 38 }, { wch: 10 }, { wch: 18 }],
    merges: coverData?.merges,
    rowHeights: coverData?.rowHeights
  })
}

function addSheetHeader(rows: XCell[][], p: ExcelExportParams, title: string, cols: number): any[] {
  const modStr = p.module === 'Property' ? 'PROPERTIES MANAGEMENT' : 'INVESTMENT PORTFOLIO'
  const periodStr = `Period: ${p.periodLabel || 'All Time'}`
  
  const r1 = Array(cols).fill(null).map(() => eCell(C.primaryDark))
  r1[0] = hCell(`INSACC - ${modStr}`, { sz: 12, bg: C.primaryDark })

  const r2 = Array(cols).fill(null).map(() => eCell(C.subHdr))
  r2[0] = hCell(`${title.toUpperCase()}  |  ${periodStr}`, { sz: 10, bg: C.subHdr, bold: false })

  const r3 = Array(cols).fill(null).map(() => eCell())
  
  rows.push(r1, r2, r3)

  return [
    { s: { r: 0, c: 0 }, e: { r: 0, c: cols - 1 } },
    { s: { r: 1, c: 0 }, e: { r: 1, c: cols - 1 } }
  ]
}

// ── SHEET 3: TRANSACTIONS ─────────────────────────────────────────
function sheetTransactions(p: ExcelExportParams, fv: Voucher[]): any {
  const rows: XCell[][] = []
  const merges = addSheetHeader(rows, p, 'Transactions', 18)
  const hdrs = ['Date', 'Voucher No.', 'Ref. No.', 'Type', 'Party / Tenant / Vendor', 'Description', 'Narration', 'From Account', 'To Account', 'Payment Mode', 'Cheque No.', 'Account Code', 'Account Name', 'Debit', 'Credit', 'Running Balance', 'Posted By', 'Posted Time']
  rows.push(hdrs.map(h => hCell(h, { bg: C.primaryDark, sz: 9 })))

  const sorted = [...fv].sort((a, b) => a.date.localeCompare(b.date))
  let runBal = 0, ri = 0, totDr = 0, totCr = 0

  for (const v of sorted) {
    for (const l of v.lines) {
      const acct = p.accounts.find(a => a.id === l.accountId)
      const isDr = l.type === 'Debit'
      runBal += isDr ? l.amount : -l.amount
      if (isDr) totDr += l.amount; else totCr += l.amount
      const bg = ri % 2 === 0 ? C.rowEven : C.rowAlt; ri++

      let party = ''
      const lease = p.leases?.find(le => le.leaseNumber === v.reference)
      if (lease) { const t = p.tenants?.find(t => t.id === lease.tenantId); if (t) party = t.name }
      if (!party) party = (v.description || '').match(/from (.*?)(?:\)|$)/)?.[1] || (v.description || '').match(/paid to (.*?)(?:\)|$)/)?.[1] || ''

      let pm: string = v.type as string
      const chq = (v.description + ' ' + (l.narration || '')).match(/Chq\s*#?\s*([a-zA-Z0-9]+)/i)
      const chqNo = chq ? chq[1] : ''
      if (chq) pm = 'Cheque'
      const pt = (v.description + ' ' + (l.narration || '')).match(/Transfer|PDC|Cash|Card|Online/i)
      if (pt) pm = pt[0]

      rows.push([
        dCell(fmtD(v.date), { bg }),
        dCell(v.number, { bg, bold: true }),
        dCell(v.reference || '', { bg }),
        dCell(v.type, { bg, center: true }),
        dCell(party, { bg }),
        dCell(v.description, { bg }),
        dCell(l.narration || '', { bg, italic: true, color: C.gray }),
        dCell(isDr ? '' : (acct?.name || ''), { bg }),
        dCell(isDr ? (acct?.name || '') : '', { bg }),
        dCell(pm, { bg, center: true }),
        dCell(chqNo, { bg }),
        dCell(acct?.code || '', { bg }),
        dCell(acct?.name || '', { bg }),
        isDr ? cCell(l.amount, bg) : eCell(bg),
        !isDr ? cCell(l.amount, bg) : eCell(bg),
        cCell(runBal, bg),
        dCell(v.postedBy || v.createdBy || 'system', { bg }),
        dCell(fmtDT(v.postedAt || v.createdAt || ''), { bg }),
      ])
    }
  }

  const tot: XCell[] = Array(18).fill(null).map(() => eCell(C.totalsRow))
  tot[0] = dCell('TOTAL', { bold: true, bg: C.totalsRow })
  tot[13] = cCell(totDr, C.totalsRow, true)
  tot[14] = cCell(totCr, C.totalsRow, true)
  rows.push(tot)

  return buildWS(rows, {
    freeze: { r: 4, c: 2 }, filterRow: 3,
    colW: [{ wch: 14 }, { wch: 14 }, { wch: 14 }, { wch: 12 }, { wch: 22 }, { wch: 34 }, { wch: 28 }, { wch: 22 }, { wch: 22 }, { wch: 14 }, { wch: 12 }, { wch: 14 }, { wch: 24 }, { wch: 16 }, { wch: 16 }, { wch: 16 }, { wch: 14 }, { wch: 18 }],
    merges
  })
}

// ── SHEET 4: VOUCHER DETAILS ──────────────────────────────────────
function sheetVoucherDetails(p: ExcelExportParams, fv: Voucher[]): any {
  const rows: XCell[][] = []
  const merges = addSheetHeader(rows, p, 'Voucher Details', 13)
  const hdrs = ['Voucher No.', 'Type', 'Date', 'Currency', 'Exch. Rate', 'Total Debit', 'Total Credit', 'Net', 'Party', 'Description', 'Created By', 'Approved By', 'Reference']
  rows.push(hdrs.map(h => hCell(h, { bg: C.primaryDark, sz: 9 })))
  const lHdrs = ['', '  Line #', 'Account Code', 'Account Name', 'Dr / Cr', '', 'Debit Amount', 'Credit Amount', '', 'Line Narration', '', '', '']
  rows.push(lHdrs.map(h => hCell(h, { bg: C.subHdr, sz: 8, bold: h !== '' })))

  const sorted = [...fv].sort((a, b) => a.date.localeCompare(b.date))
  let vi = 0
  for (const v of sorted) {
    const vDr = v.lines.filter(l => l.type === 'Debit').reduce((s, l) => s + l.amount, 0)
    const vCr = v.lines.filter(l => l.type === 'Credit').reduce((s, l) => s + l.amount, 0)
    let party = ''
    if (p.module === 'Property') {
      const lease = p.leases?.find(le => le.leaseNumber === v.reference)
      const t = lease ? p.tenants?.find(t => t.id === lease.tenantId) : null
      if (t) party = t.name
    } else {
      party = (v.description || '').match(/from (.*?)(?:\)|$)/)?.[1] || (v.description || '').match(/paid to (.*?)(?:\)|$)/)?.[1] || ''
    }
    const bg = vi % 2 === 0 ? C.rowEven : C.rowAlt
    rows.push([
      dCell(v.number, { bg, bold: true }), dCell(v.type, { bg, center: true }), dCell(fmtD(v.date), { bg }),
      dCell(v.currency || p.currency, { bg, center: true }), dCell(v.exchangeRate || 1, { bg, center: true, fmt: '#,##0.0000' }),
      cCell(vDr, bg, true), cCell(vCr, bg, true), cCell(vDr - vCr, bg),
      dCell(party, { bg }), dCell(v.description, { bg }),
      dCell(v.createdBy || 'system', { bg }), dCell(v.approvedBy || '', { bg }), dCell(v.reference || '', { bg }),
    ])
    v.lines.forEach((l, li) => {
      const a = p.accounts.find(x => x.id === l.accountId)
      const lb = C.grayLight
      rows.push([
        eCell(lb), dCell(`  ${li + 1}`, { bg: lb, color: C.gray }),
        dCell(a?.code || '', { bg: lb, bold: true }), dCell(a?.name || '', { bg: lb }),
        dCell(l.type, { bg: lb, center: true, bold: true, color: l.type === 'Debit' ? C.primaryMid : C.red }),
        eCell(lb),
        l.type === 'Debit' ? cCell(l.amount, lb) : eCell(lb),
        l.type === 'Credit' ? cCell(l.amount, lb) : eCell(lb),
        eCell(lb), dCell(l.narration || '', { bg: lb, italic: true }),
        eCell(lb), eCell(lb), eCell(lb),
      ])
    })
    vi++
  }

  return buildWS(rows, {
    freeze: { r: 5, c: 1 }, filterRow: 3,
    colW: [{ wch: 14 }, { wch: 10 }, { wch: 14 }, { wch: 10 }, { wch: 14 }, { wch: 16 }, { wch: 16 }, { wch: 16 }, { wch: 22 }, { wch: 38 }, { wch: 14 }, { wch: 14 }, { wch: 16 }],
    merges
  })
}

// ── SHEET 5: BANK ACTIVITY ────────────────────────────────────────
function sheetBankActivity(p: ExcelExportParams, fv: Voucher[]): any {
  const rows: XCell[][] = []
  const merges = addSheetHeader(rows, p, 'Bank Activity', 11)
  const bankAccts = p.accounts.filter(a => (a.parentId === '1110' || a.parentId === '1120') && a.isActive)
  const sorted = [...fv].sort((a, b) => a.date.localeCompare(b.date))
  const hdrs = ['Date', 'Voucher No.', 'Type', 'Description', 'Narration', 'Payment Mode', 'Cheque No.', 'Reference', 'Money In', 'Money Out', 'Running Balance']

  if (bankAccts.length === 0) {
    rows.push([dCell('No bank accounts found.', { color: C.gray })])
    return buildWS(rows, {})
  }

  for (const ba of bankAccts) {
    rows.push(sectionRow(`  ${ba.name.toUpperCase()}   (${ba.code})`, hdrs.length, C.primaryDark))
    rows.push(hdrs.map(h => hCell(h, { bg: C.primary, sz: 9 })))

    let runBal = 0
    rows.push([
      dCell(fmtD(p.filters?.dateRange?.start || ''), { bold: true, bg: C.grayLight }),
      dCell('—', { center: true, bg: C.grayLight }), dCell('Opening', { bold: true, center: true, bg: C.grayLight }),
      dCell('Balance brought forward', { bold: true, bg: C.grayLight }),
      ...Array(6).fill(null).map(() => eCell(C.grayLight)),
      cCell(runBal, C.grayLight, true),
    ])

    let ti = 0, to = 0, xi = 0
    for (const v of sorted) {
      for (const l of v.lines) {
        if (l.accountId !== ba.id) continue
        const isDr = l.type === 'Debit'
        if (isDr) { runBal += l.amount; ti += l.amount } else { runBal -= l.amount; to += l.amount }
        const bg = xi % 2 === 0 ? C.rowEven : C.rowAlt; xi++
        let pm: string = v.type as string
        const chq = (v.description + ' ' + (l.narration || '')).match(/Chq\s*#?\s*([a-zA-Z0-9]+)/i)
        const chqNo = chq ? chq[1] : ''
        if (chq) pm = 'Cheque'
        const pt = (v.description + ' ' + (l.narration || '')).match(/Transfer|PDC|Cash|Card|Online/i)
        if (pt) pm = pt[0]
        rows.push([
          dCell(fmtD(v.date), { bg }), dCell(v.number, { bg, bold: true }), dCell(v.type, { bg, center: true }),
          dCell(v.description, { bg }), dCell(l.narration || '', { bg, italic: true, color: C.gray }),
          dCell(pm, { bg, center: true }), dCell(chqNo, { bg }), dCell(v.reference || '', { bg }),
          isDr ? cCell(l.amount, bg) : eCell(bg), !isDr ? cCell(l.amount, bg) : eCell(bg), cCell(runBal, bg),
        ])
      }
    }
    rows.push([
      dCell('CLOSING BALANCE', { bold: true, bg: C.totalsRow }),
      ...Array(7).fill(null).map(() => eCell(C.totalsRow)),
      cCell(ti, C.totalsRow, true), cCell(to, C.totalsRow, true), cCell(runBal, C.totalsRow, true),
    ])
    rows.push([]); rows.push([])
  }

  return buildWS(rows, {
    freeze: { r: 5, c: 0 },
    colW: [{ wch: 14 }, { wch: 14 }, { wch: 12 }, { wch: 34 }, { wch: 28 }, { wch: 14 }, { wch: 12 }, { wch: 16 }, { wch: 16 }, { wch: 16 }, { wch: 16 }],
    merges
  })
}

// ── SHEET 6: GENERAL LEDGER ───────────────────────────────────────
function sheetLedger(p: ExcelExportParams, fv: Voucher[]): any {
  const rows: XCell[][] = []
  const merges = addSheetHeader(rows, p, 'General Ledger', 7)
  const sorted = [...fv].sort((a, b) => a.date.localeCompare(b.date))
  const typeOrder = ['asset', 'liability', 'equity', 'revenue', 'expense']
  const typeLabels: Record<string, string> = { asset: 'ASSETS', liability: 'LIABILITIES', equity: 'EQUITY', revenue: 'REVENUE / INCOME', expense: 'EXPENSES' }
  const colHdrs = ['Date', 'Voucher No.', 'Type', 'Description', 'Debit', 'Credit', 'Running Balance']

  for (const aType of typeOrder) {
    const accs = p.accounts.filter(a => a.isActive && a.type === aType)
    if (accs.length === 0) continue
    rows.push(sectionRow(`  ${typeLabels[aType]}`, colHdrs.length, C.primaryDark))

    for (const acct of accs) {
      const txns: Array<{ v: Voucher; l: Voucher['lines'][0] }> = []
      for (const v of sorted) for (const l of v.lines) if (l.accountId === acct.id) txns.push({ v, l })
      if (txns.length === 0) continue

      rows.push([
        mkCell(`  ${acct.code}  ${acct.name}`, { font: { name: FN, bold: true, sz: 10, color: { rgb: C.white } }, fill: { fgColor: { rgb: C.subHdr } }, alignment: { horizontal: 'left', vertical: 'center' }, border: allBdr }),
        ...Array(colHdrs.length - 1).fill(null).map(() => mkCell('', { fill: { fgColor: { rgb: C.subHdr } }, border: allBdr })),
      ])
      rows.push(colHdrs.map(h => hCell(h, { bg: C.primary, sz: 9 })))

      let runBal = 0
      rows.push([
        dCell('—', { center: true, bg: C.grayLight }), dCell('OPEN', { bold: true, bg: C.grayLight }),
        dCell('Opening', { bg: C.grayLight }), dCell('Balance brought forward', { bold: true, bg: C.grayLight }),
        eCell(C.grayLight), eCell(C.grayLight), cCell(runBal, C.grayLight, true),
      ])

      let tDr = 0, tCr = 0, xi = 0
      for (const { v, l } of txns) {
        const isDr = l.type === 'Debit'
        const mult = acct.normalBalance === 'debit' ? (isDr ? 1 : -1) : (isDr ? -1 : 1)
        runBal += l.amount * mult
        if (isDr) tDr += l.amount; else tCr += l.amount
        const bg = xi % 2 === 0 ? C.rowEven : C.rowAlt; xi++
        rows.push([
          dCell(fmtD(v.date), { bg }), dCell(v.number, { bg, bold: true }), dCell(v.type, { bg, center: true }),
          dCell(v.description, { bg }),
          isDr ? cCell(l.amount, bg) : eCell(bg), !isDr ? cCell(l.amount, bg) : eCell(bg),
          cCell(runBal, bg),
        ])
      }
      rows.push([
        dCell('CLOSING BALANCE', { bold: true, bg: C.totalsRow }), eCell(C.totalsRow), eCell(C.totalsRow), eCell(C.totalsRow),
        cCell(tDr, C.totalsRow, true), cCell(tCr, C.totalsRow, true), cCell(runBal, C.totalsRow, true),
      ])
      rows.push([])
    }
    rows.push([])
  }

  return buildWS(rows, {
    freeze: { r: 4, c: 0 }, filterRow: 3,
    colW: [{ wch: 14 }, { wch: 14 }, { wch: 12 }, { wch: 38 }, { wch: 16 }, { wch: 16 }, { wch: 16 }],
    merges
  })
}

// ── SHEET 7: AUDIT TRAIL ──────────────────────────────────────────
function sheetAudit(p: ExcelExportParams): any {
  const rows: XCell[][] = []
  const merges = addSheetHeader(rows, p, 'Audit Trail', 7)
  const hdrs = ['Timestamp', 'Created By', 'Module', 'Action', 'Target / Voucher ID', 'Status', 'Details']
  rows.push(hdrs.map(h => hCell(h, { bg: C.primaryDark })))
  const logs = p.auditLogs || []
  if (logs.length === 0) {
    rows.push([dCell('No audit records found for this period.', { italic: true, color: C.gray }), ...Array(hdrs.length - 1).fill(null).map(() => eCell())])
  } else {
    logs.forEach((log: any, i: number) => {
      const bg = i % 2 === 0 ? C.rowEven : C.rowAlt
      rows.push([
        dCell(fmtDT(log.timestamp || log.createdAt || ''), { bg }),
        dCell(log.user || log.createdBy || 'system', { bg, bold: true }),
        dCell(log.module || '', { bg }),
        dCell(log.action || '', { bg }),
        dCell(log.targetId || '', { bg }),
        dCell(log.status || 'Success', { bg, center: true, color: log.status === 'Error' ? C.red : C.primaryMid }),
        dCell(log.details || log.description || '', { bg }),
      ])
    })
  }
  return buildWS(rows, { freeze: { r: 4, c: 0 }, filterRow: 3, colW: [{ wch: 22 }, { wch: 16 }, { wch: 14 }, { wch: 18 }, { wch: 24 }, { wch: 10 }, { wch: 48 }], merges })
}

// ── SHEET 8: NOTES ────────────────────────────────────────────────
function sheetNotes(p: ExcelExportParams, count: number): any {
  const rows: XCell[][] = []
  const merges = addSheetHeader(rows, p, 'Report Notes & Metadata', 3)
  const now = new Date()
  const blk = (lbl: string, val: string) => [dCell(lbl, { bold: true, color: C.gray }), dCell(val), eCell()]

  rows.push(sectionRow('  EXPORT CONFIGURATION', 3))
  rows.push(blk('Company Name', p.companyName))
  rows.push(blk('Report Title', p.reportTitle))
  rows.push(blk('Module', p.module))
  rows.push(blk('Currency', p.currency))
  rows.push(blk('Generated By', p.generatedBy))
  rows.push(blk('Generated On', fmtDT(now)))
  rows.push([])
  rows.push(sectionRow('  ACTIVE FILTERS', 3))
  rows.push(blk('Date Range', p.filters?.dateRange ? `${fmtD(p.filters.dateRange.start)}  →  ${fmtD(p.filters.dateRange.end)}` : 'All dates'))
  rows.push(blk('Voucher Type', p.filters?.voucherType || 'All'))
  rows.push(blk('Status', p.filters?.status || 'All'))
  rows.push(blk('Bank Account', p.filters?.bankAccountId && p.filters.bankAccountId !== 'All' ? (p.accounts.find(a => a.id === p.filters?.bankAccountId)?.name || p.filters.bankAccountId) : 'All'))
  rows.push(blk('Ledger Account', p.filters?.accountId && p.filters.accountId !== 'All' ? (p.accounts.find(a => a.id === p.filters?.accountId)?.name || p.filters.accountId) : 'All'))
  rows.push(blk('Asset', p.filters?.assetName || 'All'))
  rows.push(blk('Building', p.filters?.buildingName || 'All'))
  rows.push(blk('Tenant', p.filters?.tenantName || 'All'))
  rows.push([])
  rows.push(sectionRow('  STATISTICS', 3))
  rows.push(blk('Total Vouchers (After Filter)', String(count)))
  rows.push(blk('Total Active Accounts', String(p.accounts.filter(a => a.isActive).length)))
  rows.push([])
  rows.push(sectionRow('  APPLICATION INFO', 3))
  rows.push(blk('Application', 'InsAcc — Intelligent Asset & Investment Accounting'))
  rows.push(blk('Version', '1.0.0'))
  rows.push(blk('Report Format', 'Professional Excel Workbook (.xlsx)'))
  rows.push(blk('Sheets', '8 (Cover, Executive Summary, Transactions, Voucher Details, Bank Activity, General Ledger, Audit Trail, Notes)'))

  return buildWS(rows, { freeze: { r: 4, c: 0 }, colW: [{ wch: 30 }, { wch: 52 }, { wch: 10 }], landscape: false, merges })
}

function getGroupedData(p: ExcelExportParams, fv: Voucher[]): { groupName: string, lines: any[] }[] {
  const map = new Map<string, any[]>()
  
  fv.forEach(v => {
    v.lines.forEach(l => {
      // If an account filter is applied, only group the lines that match the filter.
      if (p.reportType === 'LedgerBreakup' && p.filters?.accountId && p.filters.accountId !== 'All') {
        if (l.accountId !== p.filters.accountId) return
      }

      let key = 'Uncategorized'
      
      if (p.reportType === 'LedgerBreakup') {
        key = p.accounts.find(a => a.id === l.accountId)?.name || 'Unknown Account'
      } else if (p.reportType === 'PropertyBreakup') {
        const lease = p.leases?.find(lx => lx.leaseNumber === v.reference || (l.referenceType === 'Lease' && l.referenceId === lx.id))
        const prop = p.properties?.find(px => px.id === (lease?.propertyId || (l.referenceType === 'Property' ? l.referenceId : null)))
        key = prop?.name || 'Unassigned Property'
      } else if (p.reportType === 'SupplierBreakup') {
        key = v.reference || v.description || 'Unknown Supplier'
      } else if (p.reportType === 'TenantBreakup') {
        const lease = p.leases?.find(lx => lx.leaseNumber === v.reference || (l.referenceType === 'Lease' && l.referenceId === lx.id))
        const tenant = p.tenants?.find(tx => tx.id === lease?.tenantId)
        key = tenant?.name || v.reference || 'Unknown Tenant'
      }
      
      if (!map.has(key)) map.set(key, [])
      map.get(key)!.push({
        v, l,
        accName: p.accounts.find(a => a.id === l.accountId)?.name || l.accountId,
        desc: l.narration || v.description || ''
      })
    })
  })
  
  const grouped: { groupName: string, lines: any[] }[] = []
  Array.from(map.entries()).forEach(([key, items]) => {
    grouped.push({
      groupName: key,
      lines: items
    })
  })
  
  // Sort alphabetically by groupName
  return grouped.sort((a, b) => a.groupName.localeCompare(b.groupName))
}

function sheetBreakup(p: ExcelExportParams, fv: Voucher[], coverData?: any): any {
  const rows: XCell[][] = []
  
  if (coverData) {
    rows.push(...coverData.rows, [], [])
  }
  
  const groupedData = getGroupedData(p, fv)
  
  groupedData.forEach(group => {
    let totDr = 0, totCr = 0
    group.lines.forEach((x: any) => {
      if (x.l.type === 'Debit') totDr += x.l.amount
      else totCr += x.l.amount
    })
    
    rows.push(sectionRow(`  ${group.groupName.toUpperCase()} - (Debits: ${p.currency} ${totDr.toFixed(2)} | Credits: ${p.currency} ${totCr.toFixed(2)})`, 8, C.primaryDark))
    const hdrs = ['Date', 'Voucher', 'Reference', 'Type', 'Account', 'Description', 'Debit', 'Credit']
    rows.push(hdrs.map(h => hCell(h, { bg: C.primary })))
    
    group.lines.forEach((x: any) => {
      const lb = C.grayLight
      rows.push([
        dCell(x.v.date, { bg: lb, center: true }),
        dCell(x.v.voucherNumber, { bg: lb, center: true }),
        dCell(x.v.reference || '-', { bg: lb, center: true }),
        dCell(x.v.type, { bg: lb, center: true }),
        dCell(x.accName, { bg: lb }),
        dCell(x.desc, { bg: lb }),
        x.l.type === 'Debit' ? cCell(x.l.amount, lb) : eCell(lb),
        x.l.type === 'Credit' ? cCell(x.l.amount, lb) : eCell(lb)
      ])
    })
    rows.push([]) // Spacer
  })
  
  const offset = coverData ? coverData.rows.length + 2 : 0

  return buildWS(rows, {
    freeze: { r: 1 + offset, c: 0 }, filterRow: offset,
    colW: [{ wch: 14 }, { wch: 16 }, { wch: 16 }, { wch: 14 }, { wch: 25 }, { wch: 40 }, { wch: 14 }, { wch: 14 }],
    merges: coverData?.merges,
    rowHeights: coverData?.rowHeights
  })
}

// ════════════════════════════════════════════════════════════════════
// ENTRY POINT
// ════════════════════════════════════════════════════════════════════

export function getFilteredVouchers(p: ExcelExportParams) {
  return p.vouchers.filter(v => {
    if (v.isDeleted || v.status === 'Cancelled' || v.status === 'Reversed') return false;
    if (p.filters?.dateRange) {
      if (v.date < p.filters.dateRange.start || v.date > p.filters.dateRange.end) return false
    }
    if (p.filters?.voucherType && p.filters.voucherType !== 'All') {
      if (v.type.toLowerCase() !== p.filters.voucherType.toLowerCase()) return false
    }
    if (p.filters?.status && p.filters.status !== 'All') {
      if (v.status.toLowerCase() !== p.filters.status.toLowerCase()) return false
    }
    if (p.filters?.bankAccountId && p.filters.bankAccountId !== 'All') {
      if (!v.lines.some(l => l.accountId === p.filters?.bankAccountId)) return false
    }
    if (p.filters?.accountId && p.filters.accountId !== 'All') {
      if (!v.lines.some(l => l.accountId === p.filters?.accountId)) return false
    }
    if (p.filters?.assetName && p.filters.assetName !== 'All') {
      const q = p.filters.assetName.toLowerCase()
      if (!v.lines.some(l => l.narration && l.narration.toLowerCase().includes(q)) && !(v.description || '').toLowerCase().includes(q)) return false
    }
    if (p.filters?.buildingName && p.filters.buildingName !== 'All') {
      const bName = p.filters.buildingName.toLowerCase()
      const propId = p.properties?.find(x => x.name.toLowerCase() === bName)?.id
      const isLinkedToProp = v.lines.some(l => l.referenceType === 'Property' && l.referenceId === propId)
      const lease = p.leases?.find(l => l.leaseNumber === v.reference || v.lines.some(line => line.referenceType === 'Lease' && line.referenceId === l.id))
      const isLinkedToLeaseProp = lease?.propertyId === propId
      
      if (!isLinkedToProp && !isLinkedToLeaseProp) return false
    }
    if (p.filters?.tenantName && p.filters.tenantName !== 'All') {
      const tName = p.filters.tenantName.toLowerCase()
      const tenantId = p.tenants?.find(x => x.name.toLowerCase() === tName)?.id
      const lease = p.leases?.find(l => l.leaseNumber === v.reference || v.lines.some(line => line.referenceType === 'Lease' && line.referenceId === l.id))
      const isLinkedToLeaseTenant = lease?.tenantId === tenantId
      
      if (!isLinkedToLeaseTenant) return false
    }
    return true
  })
}

export async function exportAccountingExcel(p: ExcelExportParams): Promise<string | null> {
  // 1. Filter vouchers
  const fv = getFilteredVouchers(p)

  // 2. Totals
  let totDr = 0, totCr = 0
  for (const v of fv) for (const l of v.lines) { if (l.type === 'Debit') totDr += l.amount; else totCr += l.amount }

  // 3. Build workbook
  const wb = XLSX.utils.book_new()
  wb.Props = { Title: p.reportTitle, Subject: 'InsAcc Professional Accounting Report', Author: p.generatedBy, Company: p.companyName, CreatedDate: new Date() }

  const isBreakup = p.reportType && p.reportType !== 'Standard'
  const coverData = getCoverData(p, fv.length, isBreakup ? 8 : 5)
  
  if (isBreakup) {
    XLSX.utils.book_append_sheet(wb, sheetBreakup(p, fv, coverData), '1. Breakup Report')
  } else {
    XLSX.utils.book_append_sheet(wb, sheetSummary(p, fv, totDr, totCr, coverData), '1. Executive Summary')
    XLSX.utils.book_append_sheet(wb, sheetTransactions(p, fv),          '2. Transactions')
    XLSX.utils.book_append_sheet(wb, sheetVoucherDetails(p, fv),        '3. Voucher Details')
    XLSX.utils.book_append_sheet(wb, sheetBankActivity(p, fv),          '4. Bank Activity')
    XLSX.utils.book_append_sheet(wb, sheetLedger(p, fv),                '5. General Ledger')
    XLSX.utils.book_append_sheet(wb, sheetAudit(p),                     '6. Audit Trail')
    XLSX.utils.book_append_sheet(wb, sheetNotes(p, fv.length),          '7. Notes')
  }

  // 4. Save
  const today = new Date().toISOString().slice(0, 10)
  const filename = `InsAcc_${p.module === 'Property' ? 'Properties_Management' : 'Investment_Portfolio'}_Report_${today}.xlsx`
  const buf = XLSX.write(wb, { type: 'array', bookType: 'xlsx' })
  return saveWithDialog(filename, [{ name: 'Excel Workbook', extensions: ['xlsx'] }], buf)
}

export async function exportAccountingCsv(p: ExcelExportParams): Promise<string | null> {
  const fv = getFilteredVouchers(p)
  const modStr = p.module === 'Property' ? 'Properties Management' : 'Investment'
  let csv = '\uFEFF' + `${modStr}\n${p.reportTitle}\nPeriod: ${p.periodLabel || 'All Time'}\n\nDate,Voucher No,Type,Account,Debit,Credit,Description\n`
  
  fv.forEach(v => {
    v.lines.forEach(l => {
      const acc = p.accounts.find(a => a.id === l.accountId)?.name || l.accountId
      const desc = (l.narration || v.description || '').replace(/"/g, '""')
      csv += `="${formatDate(v.date, 'DD/MM/YYYY')}",${v.number},${v.type},"${acc}",${l.type === 'Debit' ? l.amount : ''},${l.type === 'Credit' ? l.amount : ''},"${desc}"\n`
    })
  })
  
  const today = new Date().toISOString().slice(0, 10)
  const filename = `InsAcc_${p.module === 'Property' ? 'Properties_Management' : 'Investment_Portfolio'}_Report_${today}.csv`
  return saveWithDialog(filename, [{ name: 'CSV', extensions: ['csv'] }], csv)
}

function addPdfFooter(doc: any, generatedBy?: string) {
  const pageCount = doc.internal.getNumberOfPages()
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.setTextColor(150, 150, 150)
  
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    const pageHeight = doc.internal.pageSize.getHeight()
    const pageWidth = doc.internal.pageSize.getWidth()
    const footerY = pageHeight - 10
    
    // Powered By INSACC on the left
    doc.text(`Powered By INSACC`, 14, footerY, { align: 'left' })
    // Only display page numbers in the footer on the right
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - 14, footerY, { align: 'right' })
  }
}
function generatePdfCoverPage(doc: any, title: string, subtitle: string, periodLabel: string, currency: string, totalTxns?: number, moduleName?: string, generatedBy?: string): number {
  const actualGeneratedBy = generatedBy || (typeof localStorage !== 'undefined' ? localStorage.getItem('loggedInUser') : null) || 'User'
  const pageWidth = doc.internal.pageSize.getWidth()
  const centerX = pageWidth / 2

  doc.setTextColor(0, 0, 0)
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text('Sameer Ishaq Harmoudi', centerX, 15, { align: 'center' })

  doc.setDrawColor(200, 200, 200)
  doc.setLineWidth(0.5)
  doc.line(0, 23, pageWidth, 23)

  doc.setTextColor(0, 0, 0)
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text(title.toUpperCase(), centerX, 30, { align: 'center' })

  let myY = 38

  if (subtitle) {
    doc.setTextColor(100, 116, 139)
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.text(subtitle, centerX, 36, { align: 'center' })
    myY = 46
  }

  doc.setTextColor(100, 116, 139)
  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  
  const dateOptions: Intl.DateTimeFormatOptions = { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit', hour12: false }
  const generatedOn = new Date().toLocaleString('en-GB', dateOptions).replace(',', '')

  const metaItems = [
    { label: 'Reporting Period', val: periodLabel },
    { label: 'Currency', val: currency },
    { label: 'Generated By', val: actualGeneratedBy },
    { label: 'Generated On', val: generatedOn },
  ]
  if (totalTxns !== undefined) {
    metaItems.push({ label: 'Total Records', val: totalTxns.toString() })
  }

  let finalModuleName = moduleName
  if (!finalModuleName && typeof document !== 'undefined') {
    const appShell = document.querySelector('.app-shell')
    if (appShell) {
      const activeModule = appShell.getAttribute('data-module')
      if (activeModule === 'property') finalModuleName = 'Properties Management'
      else if (activeModule === 'investment') finalModuleName = 'Investment'
    }
  }
  if (finalModuleName) {
    metaItems.push({ label: 'Portfolio', val: finalModuleName })
  }

  const validMetaItems = metaItems.filter(item => item.val && String(item.val).trim() !== '')

  const columns = 3
  const rowHeight = 7
  const leftMargin = 14
  const colWidth = (pageWidth - (leftMargin * 2)) / columns
  
  validMetaItems.forEach((item, index) => {
    const col = index % columns
    const row = Math.floor(index / columns)
    
    // Left-aligned dynamic grid based on page width
    const startX = leftMargin + (col * colWidth)
    const itemY = myY + (row * rowHeight)

    doc.setFont('helvetica', 'bold')
    doc.text(item.label + ':', startX, itemY)
    
    const labelWidth = doc.getTextWidth(item.label + ': ')
    doc.setFont('helvetica', 'normal')
    doc.text(item.val, startX + labelWidth, itemY)
  })

  // Update myY based on how many rows we used
  const totalRows = Math.ceil(validMetaItems.length / columns)
  myY += (totalRows * rowHeight) + 4

  doc.setFont('helvetica', 'normal')
  doc.setTextColor(0, 0, 0)

  return myY + 7
}

export async function exportAccountingPdf(p: ExcelExportParams): Promise<string | null> {
  const doc = new jsPDF('landscape')
  const fv = getFilteredVouchers(p)
  
  let totDr = 0, totCr = 0
  fv.forEach(v => v.lines.forEach(l => { if (l.type === 'Debit') totDr += l.amount; else totCr += l.amount }))

  const moduleName = p.module === 'Property' ? 'Properties Management' : 'Investment'
  let y = generatePdfCoverPage(doc, (p.reportTitle || 'ACCOUNTING REPORT').toUpperCase(), moduleName, p.periodLabel, p.currency, fv.length, moduleName, p.generatedBy)

  // Report Page
  doc.setFontSize(18)
  doc.setTextColor(...getThemeColorArray()) // primaryDark
  doc.text(`InsAcc ${moduleName} Report`, 14, y)
  
  y += 10
  doc.setFontSize(10)
  doc.setTextColor(100, 116, 139)
  doc.text(`Generated: ${new Date().toLocaleDateString()} | Period: ${p.periodLabel}`, 14, y)

  const isBreakup = p.reportType && p.reportType !== 'Standard'
  
  if (!isBreakup) {
    y += 8
    doc.text(`Total Debits: ${p.currency} ${totDr.toLocaleString(undefined, {minimumFractionDigits: 2})} | Total Credits: ${p.currency} ${totCr.toLocaleString(undefined, {minimumFractionDigits: 2})}`, 14, y)
  }
  
  if (isBreakup) {
    const groupedData = getGroupedData(p, fv)
    groupedData.forEach((group) => {
      let totGrDr = 0, totGrCr = 0
      group.lines.forEach((x: any) => {
        if (x.l.type === 'Debit') totGrDr += x.l.amount
        else totGrCr += x.l.amount
      })
      
      const tableData: any[][] = group.lines.map((x: any) => {
        const dStr = String(x.desc || '')
        return [
          formatDate(x.v.date, 'DD/MM/YYYY'),
          x.v.number,
          x.v.reference || '-',
          x.v.type,
          x.accName,
          dStr.length > 40 ? dStr.substring(0, 40) + '...' : dStr,
          x.l.type === 'Debit' ? x.l.amount.toLocaleString(undefined, {minimumFractionDigits: 2}) : '',
          x.l.type === 'Credit' ? x.l.amount.toLocaleString(undefined, {minimumFractionDigits: 2}) : ''
        ]
      })
      
      tableData.unshift([
        { content: `${group.groupName} - Debits: ${p.currency} ${totGrDr.toLocaleString(undefined, {minimumFractionDigits: 2})} | Credits: ${p.currency} ${totGrCr.toLocaleString(undefined, {minimumFractionDigits: 2})}`, colSpan: 8, styles: { halign: 'left', fillColor: getThemeColorArray(), textColor: [255, 255, 255], fontStyle: 'bold' } }
      ])
      
      autoTable(doc, {
        startY: y + 5,
        head: [['Date', 'Voucher', 'Reference', 'Type', 'Account', 'Description', 'Debit', 'Credit']],
        body: tableData,
        theme: 'grid',
        styles: { fontSize: 8 },
        headStyles: { fillColor: [248, 251, 249], textColor: getThemeColorArray(), fontStyle: 'bold' },
        alternateRowStyles: { fillColor: [248, 251, 249] },
      })
      
      y = (doc as any).lastAutoTable.finalY + 10
      if (y > 180) {
        doc.addPage()
        y = 15
      }
    })
  } else {
    const tableData: any[][] = []
    fv.forEach(v => {
      v.lines.forEach(l => {
        const acc = p.accounts.find(a => a.id === l.accountId)?.name || l.accountId
        const desc = l.narration || v.description || ''
        tableData.push([
          formatDate(v.date, 'DD/MM/YYYY'),
          v.number,
          v.reference || '-',
          v.type,
          acc,
          desc.length > 40 ? desc.substring(0, 40) + '...' : desc,
          l.type === 'Debit' ? l.amount.toLocaleString(undefined, {minimumFractionDigits: 2}) : '',
          l.type === 'Credit' ? l.amount.toLocaleString(undefined, {minimumFractionDigits: 2}) : ''
        ])
      })
    })

    autoTable(doc, {
      startY: y + 5,
      head: [['Date', 'Voucher', 'Reference', 'Type', 'Account', 'Description', 'Debit', 'Credit']],
      body: tableData,
      theme: 'grid',
      styles: { fontSize: 8 },
      headStyles: { fillColor: getThemeColorArray(), textColor: [255, 255, 255], fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [248, 251, 249] },
    })
  }

  const today = new Date().toISOString().slice(0, 10)
  const filename = `InsAcc_${p.module === 'Property' ? 'Properties_Management' : 'Investment_Portfolio'}_Report_${today}.pdf`
  addPdfFooter(doc, p.generatedBy)
  const buf = doc.output('arraybuffer')
  return saveWithDialog(filename, [{ name: 'PDF', extensions: ['pdf'] }], buf)
}

export interface TableExportParams {
  format: 'xlsx' | 'csv' | 'pdf'
  title: string
  subtitle?: string
  filename: string
  columns: string[]
  rows: (string | number)[][]
  foot?: (string | number)[][]
  periodLabel?: string
  currency?: string
  orientation?: 'portrait' | 'landscape'
  moduleName?: string
  generatedBy?: string
}

export interface SideBySideExportParams {
  format?: 'pdf' | 'xlsx' | 'csv'
  title: string
  subtitle?: string
  filename: string
  periodLabel?: string
  currency?: string
  generatedBy?: string
  leftCol: {
    title: string
    rows: any[][]
    total: number
    accentColor: string
  }
  rightCol: {
    title: string
    rows: any[][]
    total: number
    accentColor: string
  }
  footer: {
    label: string
    value: number
  }
  moduleName?: string
}

export async function exportSideBySideReport(p: SideBySideExportParams): Promise<string | null> {
  p.leftCol.rows = formatRows(p.leftCol.rows)
  p.rightCol.rows = formatRows(p.rightCol.rows)
  p.leftCol.total = roundDecimals(p.leftCol.total)
  p.rightCol.total = roundDecimals(p.rightCol.total)
  p.footer.value = roundDecimals(p.footer.value)

  const format = p.format || 'pdf'

  if (format === 'xlsx') {
    const wb = XLSX.utils.book_new()
    const now = new Date()
    const exportedOn = now.toLocaleDateString('en-GB', { day: '2-digit', month: '2-digit', year: 'numeric' })
    const wsData: any[][] = [
      ['Sameer Ishaq Harmoudi'],
      [p.moduleName || ''],
      [p.title],
      ...(p.subtitle ? [[p.subtitle]] : []),
      [`Exported on ${exportedOn}`],
      [`Period: ${p.periodLabel || 'All Time'}`],
      [],
      [p.leftCol.title, '', '', p.rightCol.title, ''],
      ['Account', 'Amount', '', 'Account', 'Amount']
    ]

    const maxRows = Math.max(p.leftCol.rows.length, p.rightCol.rows.length)
    for (let i = 0; i < maxRows; i++) {
      const lRow = p.leftCol.rows[i] || ['', '']
      const rRow = p.rightCol.rows[i] || ['', '']
      wsData.push([
        lRow[0],
        typeof lRow[1] === 'string' ? parseFloat(lRow[1].replace(/,/g, '')) || 0 : lRow[1] || 0,
        '',
        rRow[0],
        typeof rRow[1] === 'string' ? parseFloat(rRow[1].replace(/,/g, '')) || 0 : rRow[1] || 0
      ])
    }

    wsData.push(['Total', p.leftCol.total, '', 'Total', p.rightCol.total])
    wsData.push([])
    wsData.push([p.footer.label, p.footer.value])

    const ws = XLSX.utils.aoa_to_sheet(wsData)
    ws['!cols'] = [{ wch: 40 }, { wch: 15 }, { wch: 5 }, { wch: 40 }, { wch: 15 }]
    XLSX.utils.book_append_sheet(wb, ws, 'Report')

    const buf = XLSX.write(wb, { type: 'array', bookType: 'xlsx' })
    return saveWithDialog(`${p.filename}.xlsx`, [{ name: 'Excel', extensions: ['xlsx'] }], buf)
  }

  if (format === 'csv') {
    const esc = (v: any) => {
      const s = String(v || '')
      return (s.includes(',') || s.includes('"') || s.includes('\n')) ? `"${s.replace(/"/g, '""')}"` : s
    }
    const lines = [
      esc('Sameer Ishaq Harmoudi'),
      esc(p.moduleName || ''),
      esc(p.title),
      ...(p.subtitle ? [esc(p.subtitle)] : []),
      `Period: ${p.periodLabel || 'All Time'}`,
      '',
      `${esc(p.leftCol.title)},,,,${esc(p.rightCol.title)}`,
      'Account,Amount,,Account,Amount'
    ]
    const maxRows = Math.max(p.leftCol.rows.length, p.rightCol.rows.length)
    for (let i = 0; i < maxRows; i++) {
      const lRow = p.leftCol.rows[i] || ['', '']
      const rRow = p.rightCol.rows[i] || ['', '']
      lines.push(`${esc(lRow[0])},${esc(typeof lRow[1] === 'string' ? lRow[1].replace(/,/g, '') : lRow[1])},,${esc(rRow[0])},${esc(typeof rRow[1] === 'string' ? rRow[1].replace(/,/g, '') : rRow[1])}`)
    }
    lines.push(`Total,${p.leftCol.total},,Total,${p.rightCol.total}`)
    lines.push('')
    lines.push(`${esc(p.footer.label)},${p.footer.value}`)

    const buf = new Blob(['\uFEFF' + lines.join('\n')], { type: 'text/csv;charset=utf-8;' })
    return saveWithDialog(`${p.filename}.csv`, [{ name: 'CSV', extensions: ['csv'] }], buf)
  }

  const doc = new jsPDF()
  
  let y = generatePdfCoverPage(
    doc, 
    p.title, 
    p.subtitle || '', 
    p.periodLabel || 'All Time', 
    p.currency || 'AED',
    p.leftCol.rows.length + p.rightCol.rows.length,
    p.moduleName,
    p.generatedBy
  )
  
  doc.setFontSize(16)
  doc.setTextColor(...getThemeColorArray())
  doc.text(p.title, 14, y)
  
  y += 6
  doc.setFontSize(10)
  doc.setTextColor(100, 116, 139)

  y += 10
  
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 14
  const colWidth = (pageWidth - margin * 2 - 10) / 2
  
  // Left column
  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: pageWidth - margin - colWidth },
    head: [[
      { content: p.leftCol.title, colSpan: 2, styles: { halign: 'left', fillColor: [255, 255, 255], textColor: p.leftCol.accentColor, fontStyle: 'bold', fontSize: 12 } }
    ], ['Account', 'Amount']],
    body: p.leftCol.rows,
    foot: [['Total', p.leftCol.total.toLocaleString(undefined, {minimumFractionDigits: 2})]],
    theme: 'grid',
    styles: { fontSize: 8 },
    headStyles: { fillColor: [248, 251, 249], textColor: [100, 116, 139], fontStyle: 'bold' },
    footStyles: { fillColor: [255, 255, 255], textColor: p.leftCol.accentColor, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [255, 255, 255] },
  })

  const leftY = (doc as any).lastAutoTable?.finalY || y + 50

  // Right column
  autoTable(doc, {
    startY: y,
    margin: { left: margin + colWidth + 10, right: margin },
    head: [[
      { content: p.rightCol.title, colSpan: 2, styles: { halign: 'left', fillColor: [255, 255, 255], textColor: p.rightCol.accentColor, fontStyle: 'bold', fontSize: 12 } }
    ], ['Account', 'Amount']],
    body: p.rightCol.rows,
    foot: [['Total', p.rightCol.total.toLocaleString(undefined, {minimumFractionDigits: 2})]],
    theme: 'grid',
    styles: { fontSize: 8 },
    headStyles: { fillColor: [248, 251, 249], textColor: [100, 116, 139], fontStyle: 'bold' },
    footStyles: { fillColor: [255, 255, 255], textColor: p.rightCol.accentColor, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [255, 255, 255] },
  })

  y = Math.max((doc as any).lastAutoTable?.finalY || (y + 50), leftY) + 15

  // Footer (Net Income)
  doc.setFontSize(12)
  doc.setTextColor(...getThemeColorArray())
  doc.setFont('helvetica', 'bold')
  doc.text(`${p.footer.label}: ${p.currency} ${p.footer.value.toLocaleString(undefined, {minimumFractionDigits: 2})}`, 14, y)

  addPdfFooter(doc, p.generatedBy)
  const buf = doc.output('arraybuffer')
  return saveWithDialog(`${p.filename}.pdf`, [{ name: 'PDF', extensions: ['pdf'] }], buf)
}

export async function exportTableData(p: TableExportParams): Promise<string | null> {
  const columnsToRemove = ['status', 'posting', 'posting status']
  const indicesToRemove: number[] = []
  
  p.columns = p.columns.filter((col, i) => {
    if (columnsToRemove.includes(col.toLowerCase())) {
      indicesToRemove.push(i)
      return false
    }
    return true
  })

  p.rows = formatRows(p.rows.map(row => row.filter((_, i) => !indicesToRemove.includes(i))))
  if (p.foot) p.foot = formatRows(p.foot.map(row => row.filter((_, i) => !indicesToRemove.includes(i))))

  if (p.format === 'csv') {
    const esc = (v: string | number | undefined | null) => {
      if (v === null || v === undefined) return ''
      const s = String(v)
      if (/^\d{2}\/\d{2}\/\d{4}$/.test(s)) return `="${s}"`
      return (s.includes(',') || s.includes('"') || s.includes('\n')) ? `"${s.replace(/"/g, '""')}"` : s
    }
    
    const lines = [
      ...(p.moduleName ? [p.moduleName] : []),
      p.title,
      ...(p.subtitle ? [p.subtitle] : []),
      `Period: ${p.periodLabel || 'All Time'}`,
      '',
      p.columns.map(esc).join(','),
      ...p.rows.map(r => r.map(esc).join(',')),
      ...(p.foot ? p.foot.map(r => r.map(esc).join(',')) : [])
    ]
    const buf = new Blob(['\uFEFF' + lines.join('\n')], { type: 'text/csv;charset=utf-8;' })
    return saveWithDialog(`${p.filename}.csv`, [{ name: 'CSV', extensions: ['csv'] }], buf)
  }

  if (p.format === 'pdf') {
    const doc = new jsPDF({ orientation: p.orientation || 'portrait' })
    
    let y = generatePdfCoverPage(
      doc, 
      p.title, 
      p.subtitle || '', 
      p.periodLabel || 'All Time', 
      p.currency || 'AED',
      p.rows.length,
      p.moduleName,
      p.generatedBy
    )

    // Report Page — title already on cover page, only show subtitle if present
    if (p.subtitle) {
      doc.setFontSize(13)
      doc.setTextColor(...getThemeColorArray())
      doc.text(p.subtitle, 14, y)
    }

    autoTable(doc, {
      startY: y + 8,
      head: [p.columns],
      body: p.rows,
      foot: p.foot,
      showFoot: 'lastPage',
      theme: 'grid',
      styles: { fontSize: 9 },
      headStyles: { fillColor: getThemeColorArray(), textColor: [255, 255, 255], fontStyle: 'bold' },
      footStyles: { fillColor: [248, 251, 249], textColor: getThemeColorArray(), fontStyle: 'bold', lineWidth: { top: 0.5, bottom: 0.1, left: 0.1, right: 0.1 }, lineColor: getThemeColorArray() },
      alternateRowStyles: { fillColor: [248, 251, 249] },
    })

    addPdfFooter(doc, p.generatedBy)
    const buf = doc.output('arraybuffer')
    return saveWithDialog(`${p.filename}.pdf`, [{ name: 'PDF', extensions: ['pdf'] }], buf)
  }

  if (p.format === 'xlsx') {
    const wb = XLSX.utils.book_new()
    
    const now = new Date()
    const exportedOn = now.toLocaleDateString('en-GB', { day: '2-digit', month: '2-digit', year: 'numeric' })
    
    // Row layout matching reference:
    // Row 1: Company name
    // Row 2: Module name
    // Row 3: Report title (bold)
    // Row 4: Exported on date
    // Row 5: Period
    // Row 6: Blank
    // Row 7: Column headers
    // Row 8+: Data rows
    const prefixRows: any[][] = [
      ['Sameer Ishaq Harmoudi'],
      [p.moduleName || ''],
      [p.title],
      [`Exported on ${exportedOn}`],
      [`Period: ${p.periodLabel || 'All Time'}`],
      []  // blank row
    ]
    const headerRowIdx = prefixRows.length  // 0-based index = 6 (row 7)
    
    const wsData = [
      ...prefixRows,
      p.columns,
      ...p.rows,
      ...(p.foot || [])
    ]
    const ws = XLSX.utils.aoa_to_sheet(wsData)
    
    // Style: Row 1 — company name, italic
    if (ws['A1']) ws['A1'].s = { font: { sz: 11, italic: true } }
    
    // Style: Row 2 — module name
    if (ws['A2']) ws['A2'].s = { font: { sz: 10 } }
    
    // Style: Row 3 — report title, large bold
    if (ws['A3']) ws['A3'].s = { font: { sz: 14, bold: true } }
    
    // Style: Row 4 — exported on, small
    if (ws['A4']) ws['A4'].s = { font: { sz: 9 } }
    
    // Style: Row 5 — period, small
    if (ws['A5']) ws['A5'].s = { font: { sz: 9 } }

    // Style: Column headers (row 7, index 6) — bold, bottom border only, no fill
    const headerFont = { bold: true, sz: 9 }
    const headerBorder = {
      bottom: { style: 'medium', color: { rgb: '000000' } }
    }
    for (let c = 0; c < p.columns.length; c++) {
      const cellRef = XLSX.utils.encode_cell({ r: headerRowIdx, c })
      if (ws[cellRef]) {
        ws[cellRef].s = { font: headerFont, border: headerBorder, alignment: { vertical: 'center' } }
      }
    }
    
    // Style: Data rows — thin bottom border only, no fills
    const totalDataRows = p.rows.length
    const dataBorder = {
      bottom: { style: 'hair', color: { rgb: 'BBBBBB' } }
    }
    for (let r = 0; r < totalDataRows; r++) {
      const rowIdx = headerRowIdx + 1 + r
      for (let c = 0; c < p.columns.length; c++) {
        const cellRef = XLSX.utils.encode_cell({ r: rowIdx, c })
        if (ws[cellRef]) {
          ws[cellRef].s = {
            font: { sz: 9 },
            border: dataBorder,
            alignment: { vertical: 'center' }
          }
        }
      }
    }

    // Style: Footer/total rows — bold, thick top border, no fill
    if (p.foot) {
      for (let r = 0; r < p.foot.length; r++) {
        const rowIdx = headerRowIdx + 1 + totalDataRows + r
        for (let c = 0; c < p.columns.length; c++) {
          const cellRef = XLSX.utils.encode_cell({ r: rowIdx, c })
          if (ws[cellRef]) {
            ws[cellRef].s = {
              font: { bold: true, sz: 9 },
              border: { top: { style: 'medium', color: { rgb: '000000' } } }
            }
          }
        }
      }
    }
    
    // Auto column widths: measure max char length per column
    const colWidths = p.columns.map((col: string, ci: number) => {
      let maxLen = String(col).length
      for (const row of p.rows) {
        const cellVal = row[ci] !== undefined && row[ci] !== null ? String(row[ci]) : ''
        if (cellVal.length > maxLen) maxLen = cellVal.length
      }
      // clamp between 8 and 35
      return { wch: Math.min(35, Math.max(8, maxLen + 2)) }
    })
    ws['!cols'] = colWidths
    
    // Row heights
    ws['!rows'] = [
      { hpx: 18 },  // row 1: company
      { hpx: 16 },  // row 2: module
      { hpx: 22 },  // row 3: title
      { hpx: 14 },  // row 4: exported on
      { hpx: 14 },  // row 5: period
      { hpx: 6 },   // row 6: blank
      { hpx: 20 },  // row 7: headers
    ]
    
    XLSX.utils.book_append_sheet(wb, ws, 'Report')
    const buf = XLSX.write(wb, { type: 'array', bookType: 'xlsx' })
    return saveWithDialog(`${p.filename}.xlsx`, [{ name: 'Excel', extensions: ['xlsx'] }], buf)
  }

  return null
}

export interface FinancialOverviewExportParams {
  title: string
  subtitle: string
  filename: string
  currency: string
  kpis: { label: string; value: number; color: string }[]
  summary: {
    initialCapital: number
    currentAssets: number
    revenue: number
    expenses: number
    growth: number
  }
  recentActivity: any[][]
  moduleName?: string
  generatedBy?: string
}

export async function exportFinancialOverviewPdf(p: FinancialOverviewExportParams): Promise<string | null> {
  p.recentActivity = formatRows(p.recentActivity)
  p.kpis.forEach(k => { k.value = roundDecimals(k.value) })
  p.summary.initialCapital = roundDecimals(p.summary.initialCapital)
  p.summary.currentAssets = roundDecimals(p.summary.currentAssets)
  p.summary.revenue = roundDecimals(p.summary.revenue)
  p.summary.expenses = roundDecimals(p.summary.expenses)
  p.summary.growth = roundDecimals(p.summary.growth)

  const doc = new jsPDF('portrait')
  
  // 1. Cover Page
  let y = generatePdfCoverPage(doc, p.title.toUpperCase(), p.subtitle, 'YTD', p.currency, p.recentActivity.length, p.moduleName, p.generatedBy)
  
  // 2. Report Header
  doc.setFontSize(18)
  doc.setTextColor(...getThemeColorArray()) // primaryDark
  doc.text(`InsAcc ${p.title}`, 14, y)
  
  y += 10
  doc.setFontSize(10)
  doc.setTextColor(100, 116, 139)
  doc.text(`Generated: ${new Date().toLocaleDateString()} | Period: YTD`, 14, y)

  y += 15

  // 3. KPI Cards (4 in a row, fits in 210mm portrait)
  const cardWidth = 42
  const cardHeight = 22
  let x = 14
  
  p.kpis.forEach((kpi) => {
    // Draw box
    doc.setDrawColor(226, 232, 240) // light border
    doc.setFillColor(255, 255, 255)
    doc.roundedRect(x, y, cardWidth, cardHeight, 2, 2, 'FD')

    // Label
    doc.setFontSize(8)
    doc.setTextColor(100, 116, 139)
    doc.text(kpi.label.toUpperCase(), x + 3, y + 7)

    // Value
    doc.setFontSize(12)
    doc.setTextColor(...getThemeColorArray()) // standard dark green for values
    doc.setFont('helvetica', 'bold')
    doc.text(`${p.currency} ${kpi.value.toLocaleString(undefined, {minimumFractionDigits: 2})}`, x + 3, y + 16)
    doc.setFont('helvetica', 'normal')
    
    x += cardWidth + 4 // 4mm spacing
  })

  y += cardHeight + 8

  // 4. Quick Financial Summary Box
  doc.setDrawColor(226, 232, 240)
  doc.setFillColor(248, 251, 249) // light green background for summary
  doc.roundedRect(14, y, 180, 25, 2, 2, 'FD')

  doc.setFontSize(9)
  doc.setTextColor(...getThemeColorArray())
  doc.setFont('helvetica', 'bold')
  doc.text('Quick Financial Summary', 18, y + 7)
  doc.setFont('helvetica', 'normal')

  const summaryLabels = ['INITIAL CAPITAL', 'CURRENT ASSETS', 'REVENUE', 'EXPENSES', 'GROWTH']
  const summaryValues = [
    `${p.currency} ${p.summary.initialCapital.toLocaleString(undefined, {minimumFractionDigits: 2})}`,
    `${p.currency} ${p.summary.currentAssets.toLocaleString(undefined, {minimumFractionDigits: 2})}`,
    `${p.currency} ${p.summary.revenue.toLocaleString(undefined, {minimumFractionDigits: 2})}`,
    `${p.currency} ${p.summary.expenses.toLocaleString(undefined, {minimumFractionDigits: 2})}`,
    `${p.summary.growth > 0 ? '+' : ''}${p.summary.growth.toFixed(1)}%`
  ]

  let sx = 18
  const sWidth = 35
  for (let i = 0; i < 5; i++) {
    doc.setFontSize(7)
    doc.setTextColor(100, 116, 139)
    doc.text(summaryLabels[i], sx, y + 15)
    
    doc.setFontSize(9)
    doc.setTextColor(17, 24, 39)
    doc.text(summaryValues[i], sx, y + 21)
    sx += sWidth
  }

  y += 25 + 10

  // 5. Recent Accounting Activity Table
  doc.setFontSize(12)
  doc.setTextColor(...getThemeColorArray())
  doc.setFont('helvetica', 'bold')
  doc.text('Recent Accounting Activity', 14, y + 5)
  doc.setFont('helvetica', 'normal')

  autoTable(doc, {
    startY: y + 8,
    head: [['Date', 'Voucher', 'Type', 'Description', 'Amount']],
    body: p.recentActivity,
    theme: 'grid',
    styles: { fontSize: 8 },
    headStyles: { fillColor: getThemeColorArray(), textColor: [255, 255, 255], fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 251, 249] },
    columnStyles: {
      4: { halign: 'right' }
    }
  })

  addPdfFooter(doc, p.generatedBy)

  const buf = doc.output('arraybuffer')
  return saveWithDialog(`${p.filename}.pdf`, [{ name: 'PDF', extensions: ['pdf'] }], buf)
}

export { generatePdf, generateExcel, generateCsv }

// ════════════════════════════════════════════════════════════════════
// OVERVIEW PDF — Mirrors the 8-tab Excel workbook
// ════════════════════════════════════════════════════════════════════

function pdfSectionBanner(doc: any, title: string, y: number): number {
  const pw = doc.internal.pageSize.getWidth()
  doc.setFillColor(...getThemeColorArray())
  doc.rect(0, y, pw, 10, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.text(title, 14, y + 7)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(0, 0, 0)
  return y + 14
}

function pdfSubHeader(doc: any, text: string, y: number): number {
  const pw = doc.internal.pageSize.getWidth()
  doc.setFillColor(30, 58, 47) // subHdr
  doc.rect(14, y, pw - 28, 7, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'bold')
  doc.text(text, 16, y + 5)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(0, 0, 0)
  return y + 10
}

function pdfCheckNewPage(doc: any, y: number, needed: number = 30): number {
  const ph = doc.internal.pageSize.getHeight()
  if (y + needed > ph - 20) {
    doc.addPage()
    return 15
  }
  return y
}

export async function exportOverviewPdf(p: ExcelExportParams): Promise<string | null> {
  const doc = new jsPDF('landscape')
  const fv = getFilteredVouchers(p)
  const sorted = [...fv].sort((a, b) => a.date.localeCompare(b.date))
  const pw = doc.internal.pageSize.getWidth()

  let totDr = 0, totCr = 0
  fv.forEach(v => v.lines.forEach(l => { if (l.type === 'Debit') totDr += l.amount; else totCr += l.amount }))

  const moduleName = p.module === 'Property' ? 'Properties Management' : 'Investment'

  // ─── PAGE 1: COVER + EXECUTIVE SUMMARY ─────────────────────────
  let y = generatePdfCoverPage(doc, 'OVERVIEW REPORT', moduleName, p.periodLabel, p.currency, fv.length, moduleName, p.generatedBy)

  y = pdfSectionBanner(doc, 'EXECUTIVE SUMMARY', y)

  // KPIs
  let incTot = 0, expTot = 0
  for (const v of fv) {
    for (const l of v.lines) {
      const a = p.accounts.find(x => x.id === l.accountId)
      if (!a) continue
      if (a.type === 'revenue' && l.type === 'Credit') incTot += l.amount
      if (a.type === 'expense' && l.type === 'Debit') expTot += l.amount
    }
  }

  const fmt2 = (n: number) => `${p.currency} ${n.toLocaleString(undefined, { minimumFractionDigits: 2 })}`

  const kpiData = [
    ['Total Vouchers', String(fv.length), `Period: ${p.periodLabel}`],
    ['Total Debit', fmt2(totDr), 'Sum of all debit entries'],
    ['Total Credit', fmt2(totCr), 'Sum of all credit entries'],
    ['Net Movement', fmt2(totDr - totCr), 'Debit minus Credit'],
    ['Total Income', fmt2(incTot), 'Revenue account credits'],
    ['Total Expenses', fmt2(expTot), 'Expense account debits'],
    ['Net Profit / (Loss)', fmt2(incTot - expTot), 'Income minus Expenses'],
  ]

  autoTable(doc, {
    startY: y,
    head: [['Metric', 'Value', 'Notes']],
    body: kpiData,
    theme: 'grid',
    styles: { fontSize: 8 },
    headStyles: { fillColor: [34, 164, 93], textColor: [255, 255, 255], fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 251, 249] },
    columnStyles: { 0: { fontStyle: 'bold' }, 2: { textColor: [100, 116, 139], fontStyle: 'italic' } },
  })
  y = (doc as any).lastAutoTable.finalY + 8

  // Monthly Breakdown
  const months: Record<string, { inc: number; exp: number; cnt: number }> = {}
  for (const v of fv) {
    const m = v.date.slice(0, 7)
    if (!months[m]) months[m] = { inc: 0, exp: 0, cnt: 0 }
    months[m].cnt++
    for (const l of v.lines) {
      const a = p.accounts.find(x => x.id === l.accountId)
      if (!a) continue
      if (a.type === 'revenue' && l.type === 'Credit') months[m].inc += l.amount
      if (a.type === 'expense' && l.type === 'Debit') months[m].exp += l.amount
    }
  }
  const mKeys = Object.keys(months).sort()
  if (mKeys.length > 0) {
    y = pdfCheckNewPage(doc, y, 40)
    y = pdfSubHeader(doc, '  MONTHLY BREAKDOWN', y)
    const monthRows = mKeys.map(m => {
      const { inc, exp, cnt } = months[m]
      return [formatMonth(m), String(cnt), fmt2(inc), fmt2(exp), fmt2(inc - exp)]
    })
    const tI = mKeys.reduce((s, m) => s + months[m].inc, 0)
    const tE = mKeys.reduce((s, m) => s + months[m].exp, 0)
    monthRows.push(['TOTAL', String(fv.length), fmt2(tI), fmt2(tE), fmt2(tI - tE)])

    autoTable(doc, {
      startY: y,
      head: [['Month', 'Transactions', 'Income', 'Expenses', 'Net']],
      body: monthRows,
      theme: 'grid',
      styles: { fontSize: 8 },
      headStyles: { fillColor: [34, 164, 93], textColor: [255, 255, 255], fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [248, 251, 249] },
      columnStyles: { 1: { halign: 'center' }, 2: { halign: 'right' }, 3: { halign: 'right' }, 4: { halign: 'right' } },
    })
    y = (doc as any).lastAutoTable.finalY + 8
  }

  // ─── PAGE 3: TRANSACTIONS ───────────────────────────────────────
  doc.addPage()
  y = pdfSectionBanner(doc, '3. TRANSACTIONS', 10)

  const txnRows: any[][] = []
  let runBal = 0
  for (const v of sorted) {
    for (const l of v.lines) {
      const acct = p.accounts.find(a => a.id === l.accountId)
      const isDr = l.type === 'Debit'
      runBal += isDr ? l.amount : -l.amount

      let party = ''
      const lease = p.leases?.find(le => le.leaseNumber === v.reference)
      if (lease) { const t = p.tenants?.find(t => t.id === lease.tenantId); if (t) party = t.name }
      if (!party) party = (v.description || '').match(/from (.*?)(?:\)|$)/)?.[1] || (v.description || '').match(/paid to (.*?)(?:\)|$)/)?.[1] || ''

      txnRows.push([
        formatDate(v.date, 'DD/MM/YYYY'),
        v.number,
        v.reference || '-',
        v.type,
        party.length > 20 ? party.substring(0, 20) + '...' : party,
        (v.description || '').length > 35 ? v.description.substring(0, 35) + '...' : v.description,
        acct?.code || '',
        acct?.name || '',
        isDr ? l.amount.toLocaleString(undefined, { minimumFractionDigits: 2 }) : '',
        !isDr ? l.amount.toLocaleString(undefined, { minimumFractionDigits: 2 }) : '',
        runBal.toLocaleString(undefined, { minimumFractionDigits: 2 }),
      ])
    }
  }

  // Add Totals Row
  txnRows.push([
    { content: 'TOTAL', colSpan: 8, styles: { halign: 'right', fontStyle: 'bold', fillColor: [230, 240, 235] } },
    { content: totDr.toLocaleString(undefined, { minimumFractionDigits: 2 }), styles: { fontStyle: 'bold', fillColor: [230, 240, 235] } },
    { content: totCr.toLocaleString(undefined, { minimumFractionDigits: 2 }), styles: { fontStyle: 'bold', fillColor: [230, 240, 235] } },
    { content: runBal.toLocaleString(undefined, { minimumFractionDigits: 2 }), styles: { fontStyle: 'bold', fillColor: [230, 240, 235] } }
  ])

  autoTable(doc, {
    startY: y,
    head: [['Date', 'Voucher', 'Ref', 'Type', 'Party', 'Description', 'Code', 'Account', 'Debit', 'Credit', 'Balance']],
    body: txnRows,
    theme: 'grid',
    styles: { fontSize: 7 },
    headStyles: { fillColor: getThemeColorArray(), textColor: [255, 255, 255], fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 251, 249] },
    columnStyles: { 8: { halign: 'right' }, 9: { halign: 'right' }, 10: { halign: 'right' } },
  })

  // ─── PAGE 4: VOUCHER DETAILS ────────────────────────────────────
  doc.addPage()
  y = pdfSectionBanner(doc, '4. VOUCHER DETAILS', 10)

  const vdRows: any[][] = []
  for (const v of sorted) {
    const vDr = v.lines.filter(l => l.type === 'Debit').reduce((s, l) => s + l.amount, 0)
    const vCr = v.lines.filter(l => l.type === 'Credit').reduce((s, l) => s + l.amount, 0)
    let party = ''
    if (p.module === 'Property') {
      const lease = p.leases?.find(le => le.leaseNumber === v.reference)
      const t = lease ? p.tenants?.find(t => t.id === lease.tenantId) : null
      if (t) party = t.name
    } else {
      party = (v.description || '').match(/from (.*?)(?:\)|$)/)?.[1] || (v.description || '').match(/paid to (.*?)(?:\)|$)/)?.[1] || ''
    }

    // Voucher header row
    vdRows.push([
      { content: `${v.number}  |  ${v.type}  |  ${formatDate(v.date, 'DD/MM/YYYY')}  |  ${party}  |  Dr: ${fmt2(vDr)}  Cr: ${fmt2(vCr)}`, colSpan: 7, styles: { fillColor: [30, 58, 47], textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 7 } }
    ])

    // Line items
    v.lines.forEach((l, li) => {
      const a = p.accounts.find(x => x.id === l.accountId)
      vdRows.push([
        `  ${li + 1}`,
        a?.code || '',
        a?.name || '',
        l.type,
        l.type === 'Debit' ? l.amount.toLocaleString(undefined, { minimumFractionDigits: 2 }) : '',
        l.type === 'Credit' ? l.amount.toLocaleString(undefined, { minimumFractionDigits: 2 }) : '',
        (l.narration || '').length > 40 ? (l.narration || '').substring(0, 40) + '...' : (l.narration || ''),
      ])
    })
  }

  autoTable(doc, {
    startY: y,
    head: [['#', 'Code', 'Account', 'Dr/Cr', 'Debit', 'Credit', 'Narration']],
    body: vdRows,
    theme: 'grid',
    styles: { fontSize: 7 },
    headStyles: { fillColor: [34, 164, 93], textColor: [255, 255, 255], fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 251, 249] },
    columnStyles: { 4: { halign: 'right' }, 5: { halign: 'right' } },
  })

  // ─── PAGE 5: BANK ACTIVITY ──────────────────────────────────────
  doc.addPage()
  y = pdfSectionBanner(doc, '5. BANK ACTIVITY', 10)

  const bankAccts = p.accounts.filter(a => (a.parentId === '1110' || a.parentId === '1120') && a.isActive)

  if (bankAccts.length === 0) {
    doc.setFontSize(9)
    doc.setTextColor(100, 116, 139)
    doc.text('No bank accounts found.', 14, y + 5)
    y += 12
  } else {
    for (const ba of bankAccts) {
      y = pdfCheckNewPage(doc, y, 40)
      y = pdfSubHeader(doc, `  ${ba.name.toUpperCase()}  (${ba.code})`, y)

      const baRows: any[][] = []
      let bRunBal = 0, bIn = 0, bOut = 0

      // Opening balance row
      baRows.push([
        formatDate(p.filters?.dateRange?.start || '', 'DD/MM/YYYY'),
        '—', 'Opening', 'Balance brought forward', '', '', '',
        bRunBal.toLocaleString(undefined, { minimumFractionDigits: 2 })
      ])

      for (const v of sorted) {
        for (const l of v.lines) {
          if (l.accountId !== ba.id) continue
          const isDr = l.type === 'Debit'
          if (isDr) { bRunBal += l.amount; bIn += l.amount } else { bRunBal -= l.amount; bOut += l.amount }
          baRows.push([
            formatDate(v.date, 'DD/MM/YYYY'),
            v.number,
            v.type,
            (v.description || '').length > 35 ? v.description.substring(0, 35) + '...' : v.description,
            v.reference || '-',
            isDr ? l.amount.toLocaleString(undefined, { minimumFractionDigits: 2 }) : '',
            !isDr ? l.amount.toLocaleString(undefined, { minimumFractionDigits: 2 }) : '',
            bRunBal.toLocaleString(undefined, { minimumFractionDigits: 2 }),
          ])
        }
      }

      // Closing balance
      baRows.push([
        { content: `CLOSING  |  Money In: ${fmt2(bIn)}  |  Money Out: ${fmt2(bOut)}  |  Balance: ${fmt2(bRunBal)}`, colSpan: 8, styles: { fillColor: [232, 245, 237], fontStyle: 'bold', fontSize: 7 } }
      ])

      autoTable(doc, {
        startY: y,
        head: [['Date', 'Voucher', 'Type', 'Description', 'Ref', 'Money In', 'Money Out', 'Balance']],
        body: baRows,
        theme: 'grid',
        styles: { fontSize: 7 },
        headStyles: { fillColor: [34, 164, 93], textColor: [255, 255, 255], fontStyle: 'bold' },
        alternateRowStyles: { fillColor: [248, 251, 249] },
        columnStyles: { 5: { halign: 'right' }, 6: { halign: 'right' }, 7: { halign: 'right' } },
      })
      y = (doc as any).lastAutoTable.finalY + 10
    }
  }

  // ─── PAGE 6: GENERAL LEDGER ─────────────────────────────────────
  doc.addPage()
  y = pdfSectionBanner(doc, '6. GENERAL LEDGER', 10)

  const typeOrder = ['asset', 'liability', 'equity', 'revenue', 'expense']
  const typeLabels: Record<string, string> = { asset: 'ASSETS', liability: 'LIABILITIES', equity: 'EQUITY', revenue: 'REVENUE / INCOME', expense: 'EXPENSES' }

  for (const aType of typeOrder) {
    const accs = p.accounts.filter(a => a.isActive && a.type === aType)
    if (accs.length === 0) continue

    y = pdfCheckNewPage(doc, y, 30)
    y = pdfSubHeader(doc, `  ${typeLabels[aType]}`, y)

    for (const acct of accs) {
      const txns: Array<{ v: Voucher; l: Voucher['lines'][0] }> = []
      for (const v of sorted) for (const l of v.lines) if (l.accountId === acct.id) txns.push({ v, l })
      if (txns.length === 0) continue

      y = pdfCheckNewPage(doc, y, 30)

      const ledgerRows: any[][] = []

      // Opening balance
      let lRunBal = 0
      ledgerRows.push([
        '—', 'OPEN', 'Opening', 'Balance brought forward', '', '',
        lRunBal.toLocaleString(undefined, { minimumFractionDigits: 2 })
      ])

      let lDr = 0, lCr = 0
      for (const { v, l } of txns) {
        const isDr = l.type === 'Debit'
        const mult = acct.normalBalance === 'debit' ? (isDr ? 1 : -1) : (isDr ? -1 : 1)
        lRunBal += l.amount * mult
        if (isDr) lDr += l.amount; else lCr += l.amount
        ledgerRows.push([
          formatDate(v.date, 'DD/MM/YYYY'),
          v.number,
          v.type,
          (v.description || '').length > 35 ? v.description.substring(0, 35) + '...' : v.description,
          isDr ? l.amount.toLocaleString(undefined, { minimumFractionDigits: 2 }) : '',
          !isDr ? l.amount.toLocaleString(undefined, { minimumFractionDigits: 2 }) : '',
          lRunBal.toLocaleString(undefined, { minimumFractionDigits: 2 }),
        ])
      }

      // Closing
      ledgerRows.push([
        { content: `CLOSING  |  Dr: ${fmt2(lDr)}  |  Cr: ${fmt2(lCr)}  |  Balance: ${fmt2(lRunBal)}`, colSpan: 7, styles: { fillColor: [232, 245, 237], fontStyle: 'bold', fontSize: 7 } }
      ])

      // Account header + table
      autoTable(doc, {
        startY: y,
        head: [
          [{ content: `${acct.code}  ${acct.name}`, colSpan: 7, styles: { fillColor: [30, 58, 47], textColor: [255, 255, 255], fontStyle: 'bold' } }],
          ['Date', 'Voucher', 'Type', 'Description', 'Debit', 'Credit', 'Balance']
        ],
        body: ledgerRows,
        theme: 'grid',
        styles: { fontSize: 7 },
        headStyles: { fillColor: [34, 164, 93], textColor: [255, 255, 255], fontStyle: 'bold' },
        alternateRowStyles: { fillColor: [248, 251, 249] },
        columnStyles: { 4: { halign: 'right' }, 5: { halign: 'right' }, 6: { halign: 'right' } },
      })
      y = (doc as any).lastAutoTable.finalY + 6
    }
    y += 4
  }

  // ─── PAGE 7: AUDIT TRAIL ───────────────────────────────────────
  doc.addPage()
  y = pdfSectionBanner(doc, '7. AUDIT TRAIL', 10)

  const logs = p.auditLogs || []
  if (logs.length === 0) {
    autoTable(doc, {
      startY: y,
      head: [['Timestamp', 'User', 'Module', 'Action', 'Target', 'Status', 'Details']],
      body: [['No audit records found for this period.', '', '', '', '', '', '']],
      theme: 'grid',
      styles: { fontSize: 7, textColor: [100, 116, 139], fontStyle: 'italic' },
      headStyles: { fillColor: getThemeColorArray(), textColor: [255, 255, 255], fontStyle: 'bold' },
    })
  } else {
    const auditRows = logs.map((log: any) => [
      fmtDT(log.timestamp || log.createdAt || ''),
      log.user || log.createdBy || 'system',
      log.module || '',
      log.action || '',
      log.targetId || '',
      log.status || 'Success',
      (log.details || log.description || '').length > 40 ? (log.details || log.description || '').substring(0, 40) + '...' : (log.details || log.description || ''),
    ])
    autoTable(doc, {
      startY: y,
      head: [['Timestamp', 'User', 'Module', 'Action', 'Target', 'Status', 'Details']],
      body: auditRows,
      theme: 'grid',
      styles: { fontSize: 7 },
      headStyles: { fillColor: getThemeColorArray(), textColor: [255, 255, 255], fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [248, 251, 249] },
    })
  }

  // ─── PAGE 8: NOTES & METADATA ──────────────────────────────────
  doc.addPage()
  y = pdfSectionBanner(doc, '8. NOTES & METADATA', 10)

  const now = new Date()
  const dateOpts: Intl.DateTimeFormatOptions = { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit', hour12: false }

  const notesData = [
    [{ content: 'EXPORT CONFIGURATION', colSpan: 2, styles: { fillColor: [30, 58, 47], textColor: [255, 255, 255], fontStyle: 'bold' } }],
    ['Company Name', p.companyName],
    ['Report Title', 'OVERVIEW REPORT'],
    ['Module', p.module],
    ['Currency', p.currency],
    ['Generated By', p.generatedBy],
    ['Generated On', now.toLocaleString('en-GB', dateOpts).replace(',', '')],
    [{ content: 'ACTIVE FILTERS', colSpan: 2, styles: { fillColor: [30, 58, 47], textColor: [255, 255, 255], fontStyle: 'bold' } }],
    ['Date Range', p.filters?.dateRange ? `${formatDate(p.filters.dateRange.start, 'DD/MM/YYYY')}  to  ${formatDate(p.filters.dateRange.end, 'DD/MM/YYYY')}` : 'All dates'],
    ['Voucher Type', p.filters?.voucherType || 'All'],
    ['Status', p.filters?.status || 'All'],
    ['Bank Account', p.filters?.bankAccountId && p.filters.bankAccountId !== 'All' ? (p.accounts.find(a => a.id === p.filters?.bankAccountId)?.name || p.filters.bankAccountId) : 'All'],
    ['Ledger Account', p.filters?.accountId && p.filters.accountId !== 'All' ? (p.accounts.find(a => a.id === p.filters?.accountId)?.name || p.filters.accountId) : 'All'],
    [{ content: 'STATISTICS', colSpan: 2, styles: { fillColor: [30, 58, 47], textColor: [255, 255, 255], fontStyle: 'bold' } }],
    ['Total Vouchers (After Filter)', String(fv.length)],
    ['Total Active Accounts', String(p.accounts.filter(a => a.isActive).length)],
    [{ content: 'APPLICATION INFO', colSpan: 2, styles: { fillColor: [30, 58, 47], textColor: [255, 255, 255], fontStyle: 'bold' } }],
    ['Application', 'InsAcc — Intelligent Asset & Investment Accounting'],
    ['Version', '1.0.0'],
    ['Report Format', 'Professional PDF Report'],
    ['Sections', '8 (Cover, Executive Summary, Transactions, Voucher Details, Bank Activity, General Ledger, Audit Trail, Notes)'],
  ]

  autoTable(doc, {
    startY: y,
    head: [['Field', 'Value']],
    body: notesData,
    theme: 'grid',
    styles: { fontSize: 8 },
    headStyles: { fillColor: [34, 164, 93], textColor: [255, 255, 255], fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 251, 249] },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 60 } },
  })

  // Footer on all pages
  addPdfFooter(doc, p.generatedBy)
  const today = new Date().toISOString().slice(0, 10)
  const filename = `InsAcc_${p.module === 'Property' ? 'Properties_Management' : 'Investment_Portfolio'}_Overview_Report_${today}.pdf`
  const buf = doc.output('arraybuffer')
  return saveWithDialog(filename, [{ name: 'PDF', extensions: ['pdf'] }], buf)
}
